<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class OrgStructureSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'pid' => null,
                'is_active' => true,
                'firstname' => 'Edgar',
                'lastname' => 'Saavedra',
                'nickname' => 'Ed',
                'name' => 'Ed Saavedra',
                'position_title' => 'Chairman & CEO',
                'reporting' => 'Not Applicable',
                'emp_no' => '1',
                'level' => 'Executive',
                'department' => 'OCEO',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 1,
                'is_active' => true,
                'firstname' => 'Bernice Jillian',
                'lastname' => 'Hu',
                'nickname' => 'Bern',
                'name' => 'Bern Hu',
                'position_title' => 'Management Associate',
                'reporting' => 'Saavedra, Edgar (Ed)',
                'emp_no' => '68074',
                'level' => 'Manager',
                'department' => 'OCEO',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 1,
                'is_active' => false,
                'firstname' => 'Employee',
                'lastname' => 'Vacant',
                'nickname' => 'Emp',
                'name' => 'Vacant, Employee (Emp)',
                'position_title' => 'Management Associate',
                'reporting' => 'Saavedra, Edgar (Ed)',
                'emp_no' => '0',
                'level' => 'Manager',
                'department' => 'OCEO',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 1,
                'is_active' => false,
                'firstname' => 'Employee',
                'lastname' => 'Vacant',
                'nickname' => 'Emp',
                'name' => 'Vacant, Employee (Emp)',
                'position_title' => 'Management Associate',
                'reporting' => 'Saavedra, Edgar (Ed)',
                'emp_no' => '0',
                'level' => 'Manager',
                'department' => 'OCEO',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 2,
                'is_active' => true,
                'firstname' => 'Jellica Aine',
                'lastname' => 'Santos',
                'nickname' => 'Jelli',
                'name' => 'Jelli Santos',
                'position_title' => 'Management Trainee',
                'reporting' => 'Hu, Bernice Jillian (Bern)',
                'emp_no' => '20589',
                'level' => 'Supervisor / Officer',
                'department' => 'OCEO',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 2,
                'is_active' => true,
                'firstname' => 'Joland Abby',
                'lastname' => 'Batiancila',
                'nickname' => 'Abby',
                'name' => 'Abby Batiancila',
                'position_title' => 'Management Trainee',
                'reporting' => 'Hu, Bernice Jillian (Bern)',
                'emp_no' => '79792',
                'level' => 'Supervisor / Officer',
                'department' => 'OCEO',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 2,
                'is_active' => true,
                'firstname' => 'Rafael',
                'lastname' => 'Saavedra',
                'nickname' => 'Raf',
                'name' => 'Raf Saavedra',
                'position_title' => 'Management Trainee',
                'reporting' => 'Hu, Bernice Jillian (Bern)',
                'emp_no' => '105924',
                'level' => 'Supervisor / Officer',
                'department' => 'OCEO',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 2,
                'is_active' => true,
                'firstname' => 'Carvey Carrick',
                'lastname' => 'Chan',
                'nickname' => 'Carvey',
                'name' => 'Carvey Chan',
                'position_title' => 'Management Trainee',
                'reporting' => 'Hu, Bernice Jillian (Bern)',
                'emp_no' => '106024',
                'level' => 'Supervisor / Officer',
                'department' => 'OCEO',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 2,
                'is_active' => true,
                'firstname' => 'Melissa',
                'lastname' => 'Salilican',
                'nickname' => 'Myles',
                'name' => 'Myles Salilican',
                'position_title' => 'Facilities Management Officer',
                'reporting' => 'Saavedra, Edgar (Ed)',
                'emp_no' => '927',
                'level' => 'Supervisor / Officer',
                'department' => 'OCEO',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 2,
                'is_active' => true,
                'firstname' => 'Joselito',
                'lastname' => 'Nones',
                'nickname' => 'Jage',
                'name' => 'Jage Nores',
                'position_title' => 'IT Project Manager',
                'reporting' => 'Saavedra, Edgar (Ed)',
                'emp_no' => '15971',
                'level' => 'Manager',
                'department' => 'OCEO',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 2,
                'is_active' => true,
                'firstname' => 'Leo Pacholo',
                'lastname' => 'Mago',
                'nickname' => 'Lei',
                'name' => 'Lei Mago',
                'position_title' => 'Enterprise Applications Manager',
                'reporting' => 'Saavedra, Edgar (Ed)',
                'emp_no' => '28930',
                'level' => 'Manager',
                'department' => 'OCEO',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 1,
                'is_active' => true,
                'firstname' => 'Christopher',
                'lastname' => 'Nadayag',
                'nickname' => 'Chris',
                'name' => 'Chris Nadayag',
                'position_title' => 'AVP, Head of Internal Audit',
                'reporting' => 'Saavedra, Edgar (Ed)',
                'emp_no' => '726',
                'level' => 'Executive',
                'department' => 'OCHR',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 12,
                'is_active' => true,
                'firstname' => 'Ricci Angelo',
                'lastname' => 'Pasamba',
                'nickname' => 'Ricci',
                'name' => 'Ricci Pasamba',
                'position_title' => 'Internal Audit Officer',
                'reporting' => 'Nadayag, Christopher (Chris)',
                'emp_no' => '58622',
                'level' => 'Supervisor / Officer',
                'department' => 'OCHR',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 12,
                'is_active' => true,
                'firstname' => 'Errol Benedict',
                'lastname' => 'Purcia',
                'nickname' => 'Errol',
                'name' => 'Errol Purcia',
                'position_title' => 'Internal Audit Officer',
                'reporting' => 'Nadayag, Christopher (Chris)',
                'emp_no' => '83628',
                'level' => 'Supervisor / Officer',
                'department' => 'OCHR',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 16,
                'is_active' => true,
                'firstname' => 'Edmundo',
                'lastname' => 'Endrano',
                'nickname' => 'Ed',
                'name' => 'Ed Endrano',
                'position_title' => 'Driver',
                'reporting' => 'Druja, Mark Joseph (MJ)',
                'emp_no' => '739',
                'level' => 'Rank & File',
                'department' => 'OCEO',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 2,
                'is_active' => true,
                'firstname' => 'Mark Joseph',
                'lastname' => 'Druja',
                'nickname' => 'MJ',
                'name' => 'MJ Druja',
                'position_title' => 'Driver',
                'reporting' => 'Saavedra, Edgar (Ed)',
                'emp_no' => '1024',
                'level' => 'Rank & File',
                'department' => 'OCEO',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 16,
                'is_active' => true,
                'firstname' => 'Ryan',
                'lastname' => 'Viray',
                'nickname' => 'Ryan',
                'name' => 'Ryan Viray',
                'position_title' => 'Driver',
                'reporting' => 'Druja, Mark Joseph (MJ)',
                'emp_no' => '1771',
                'level' => 'Rank & File',
                'department' => 'OCEO',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 16,
                'is_active' => true,
                'firstname' => 'Nelson',
                'lastname' => 'Clerigo',
                'nickname' => 'Nelson',
                'name' => 'Nelson Clerigo',
                'position_title' => 'VIP Security',
                'reporting' => 'Druja, Mark Joseph (MJ)',
                'emp_no' => '17807',
                'level' => 'Rank & File',
                'department' => 'OCEO',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 16,
                'is_active' => true,
                'firstname' => 'Danny',
                'lastname' => 'Austero',
                'nickname' => 'Danny',
                'name' => 'Danny Austero',
                'position_title' => 'VIP Security',
                'reporting' => 'Druja, Mark Joseph (MJ)',
                'emp_no' => '24173',
                'level' => 'Rank & File',
                'department' => 'OCEO',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 16,
                'is_active' => true,
                'firstname' => 'Arnel',
                'lastname' => 'Estacoja',
                'nickname' => 'Arnel',
                'name' => 'Arriel Estacoja',
                'position_title' => 'VIP Security',
                'reporting' => 'Druja, Mark Joseph (MJ)',
                'emp_no' => '33688',
                'level' => 'Rank & File',
                'department' => 'OCEO',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 1,
                'is_active' => true,
                'firstname' => 'Jaime Raphael',
                'lastname' => 'Feliciano',
                'nickname' => 'Jim',
                'name' => 'Jim Feliciano',
                'position_title' => 'Chief Business Development Officer',
                'reporting' => 'Saavedra, Edgar (Ed)',
                'emp_no' => '7384',
                'level' => 'Executive',
                'department' => 'BDV',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 21,
                'is_active' => true,
                'firstname' => 'Stephanie Ann',
                'lastname' => 'Soon',
                'nickname' => 'Steph',
                'name' => 'Steph Soon',
                'position_title' => 'Business Development Director',
                'reporting' => 'Feliciano, Jaime Raphael (Jim)',
                'emp_no' => '19307',
                'level' => 'Manager',
                'department' => 'BDV',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 22,
                'is_active' => true,
                'firstname' => 'Danielle Marie',
                'lastname' => 'Feliciano',
                'nickname' => 'Danes',
                'name' => 'Danes Feliciano',
                'position_title' => 'Business Development Manager',
                'reporting' => 'Soon, Stephanie Ann (Steph)',
                'emp_no' => '73188',
                'level' => 'Manager',
                'department' => 'BDV',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 22,
                'is_active' => true,
                'firstname' => 'Jasmin',
                'lastname' => 'Fernandez',
                'nickname' => 'Jas',
                'name' => 'Jas Fernandez',
                'position_title' => 'Assistant Business Development Manager',
                'reporting' => 'Soon, Stephanie Ann (Steph)',
                'emp_no' => '19377',
                'level' => 'Manager',
                'department' => 'BDV',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 22,
                'is_active' => true,
                'firstname' => 'Adrian Paul',
                'lastname' => 'Flores',
                'nickname' => 'Adrian',
                'name' => 'Adrian Flores',
                'position_title' => 'Business Development Officer',
                'reporting' => 'Soon, Stephanie Ann (Steph)',
                'emp_no' => '105894',
                'level' => 'Supervisor / Officer',
                'department' => 'BDV',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 22,
                'is_active' => true,
                'firstname' => 'Rhiz Kathleen',
                'lastname' => 'Contreras',
                'nickname' => 'Kath',
                'name' => 'Kath Contreras',
                'position_title' => 'Senior Business Development Assistant',
                'reporting' => 'Soon, Stephanie Ann (Steph)',
                'emp_no' => '17334',
                'level' => 'Rank & File',
                'department' => 'BDV',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 21,
                'is_active' => true,
                'firstname' => 'Milestill',
                'lastname' => 'Young',
                'nickname' => 'Miles',
                'name' => 'Miles Young',
                'position_title' => 'Business Development Director',
                'reporting' => 'Feliciano, Jaime Raphael (Jim)',
                'emp_no' => '5283',
                'level' => 'Manager',
                'department' => 'TDV',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 27,
                'is_active' => true,
                'firstname' => 'James Matthew',
                'lastname' => 'Jaramillo',
                'nickname' => 'Matt',
                'name' => 'Matt Jaramilo',
                'position_title' => 'Business Development Officer',
                'reporting' => 'Young, Milestill (Miles)',
                'emp_no' => '19998',
                'level' => 'Supervisor / Officer',
                'department' => 'TDV',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 27,
                'is_active' => true,
                'firstname' => 'Gyan Louie',
                'lastname' => 'Gloriani',
                'nickname' => 'Gyan',
                'name' => 'Gyan Gloriani',
                'position_title' => 'Business Development Officer',
                'reporting' => 'Young, Milestill (Miles)',
                'emp_no' => '21542',
                'level' => 'Supervisor / Officer',
                'department' => 'TDV',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 27,
                'is_active' => true,
                'firstname' => 'Fernando Miguel',
                'lastname' => 'Lozano',
                'nickname' => 'Lozi',
                'name' => 'Lozi Lozano',
                'position_title' => 'Business Development Officer',
                'reporting' => 'Young, Milestill (Miles)',
                'emp_no' => '21613',
                'level' => 'Supervisor / Officer',
                'department' => 'TDV',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 1,
                'is_active' => true,
                'firstname' => 'Manuel Louie',
                'lastname' => 'Ferrer',
                'nickname' => 'LF',
                'name' => 'LF Ferrer',
                'position_title' => 'Chief Corporate Communications, Affairs & Branding Officer',
                'reporting' => 'Saavedra, Edgar (Ed)',
                'emp_no' => '1346',
                'level' => 'Executive',
                'department' => 'CCAB',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 31,
                'is_active' => true,
                'firstname' => 'Nierra Jobel',
                'lastname' => 'Azogue',
                'nickname' => 'Nierra',
                'name' => 'Nierra Azogue',
                'position_title' => 'Executive Assistant',
                'reporting' => 'Ferrer, Manuel Louie (LF)',
                'emp_no' => '19251',
                'level' => 'Supervisor / Officer',
                'department' => 'CCAB',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 31,
                'is_active' => true,
                'firstname' => 'Ericson',
                'lastname' => 'Benitez',
                'nickname' => 'Ericson',
                'name' => 'Ericson Benitez',
                'position_title' => 'Driver',
                'reporting' => 'Ferrer, Manuel Louie (LF)',
                'emp_no' => '3996',
                'level' => 'Rank & File',
                'department' => 'CCAB',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 31,
                'is_active' => false,
                'firstname' => 'Employee',
                'lastname' => 'Vacant',
                'nickname' => 'Emp',
                'name' => 'Vacant, Employee (Emp)',
                'position_title' => 'Corporate Communications and Branding Manager',
                'reporting' => 'Ferrer, Manuel Louie (LF)',
                'emp_no' => '0',
                'level' => 'Manager',
                'department' => 'CCAB',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 31,
                'is_active' => true,
                'firstname' => 'Timothy Alexander',
                'lastname' => 'Glova',
                'nickname' => 'Tim',
                'name' => 'Tim Glova',
                'position_title' => 'Stakeholder Relations Officer / Management Associate',
                'reporting' => 'Ferrer, Manuel Louie (LF)',
                'emp_no' => '19130',
                'level' => 'Supervisor / Officer',
                'department' => 'CCAB',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 1,
                'is_active' => true,
                'firstname' => 'Jez',
                'lastname' => 'Dela Cruz',
                'nickname' => 'Jez',
                'name' => 'Jez Dela Cruz',
                'position_title' => 'Group Chief Finance Officer',
                'reporting' => 'Saavedra, Edgar (Ed)',
                'emp_no' => '13067',
                'level' => 'Executive',
                'department' => 'FIN',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 36,
                'is_active' => true,
                'firstname' => 'Reza Marie',
                'lastname' => 'De Guzman',
                'nickname' => 'Reza',
                'name' => 'Reza De Guzman',
                'position_title' => 'Executive Assistant',
                'reporting' => 'Dela Cruz, Jez (Jez)',
                'emp_no' => '15682',
                'level' => 'Supervisor / Officer',
                'department' => 'FIN',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 37,
                'is_active' => true,
                'firstname' => 'John Reaner',
                'lastname' => 'Nocum',
                'nickname' => 'Rein',
                'name' => 'Rein Nocum',
                'position_title' => 'AVP, Head of Corporate Finance & Planning',
                'reporting' => 'De Guzman, Reza Marie (Reza)',
                'emp_no' => '13216',
                'level' => 'Executive',
                'department' => 'FIN',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 38,
                'is_active' => true,
                'firstname' => 'Stephanie',
                'lastname' => 'Chua',
                'nickname' => 'Steph',
                'name' => 'Steph Chua',
                'position_title' => 'Senior Corporate Finance & Planning Manager',
                'reporting' => 'Nocum, John Reaner (Rein)',
                'emp_no' => '18884',
                'level' => 'Manager',
                'department' => 'FIN',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 38,
                'is_active' => true,
                'firstname' => 'Jose Enrique',
                'lastname' => 'Sayon',
                'nickname' => 'Nico',
                'name' => 'Nico Sayon',
                'position_title' => 'Assistant Corporate Finance & Planning Manager',
                'reporting' => 'Nocum, John Reaner (Rein)',
                'emp_no' => '13819',
                'level' => 'Manager',
                'department' => 'FIN',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 38,
                'is_active' => true,
                'firstname' => 'Eric Rian',
                'lastname' => 'Lomibao',
                'nickname' => 'Eric',
                'name' => 'Eric Lomibao',
                'position_title' => 'Assistant Corporate Finance & Planning Manager',
                'reporting' => 'Nocum, John Reaner (Rein)',
                'emp_no' => '19114',
                'level' => 'Manager',
                'department' => 'FIN',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 36,
                'is_active' => true,
                'firstname' => 'Leah',
                'lastname' => 'Manalastas',
                'nickname' => 'Leah',
                'name' => 'Leah Manalastas',
                'position_title' => 'Treasury Head',
                'reporting' => 'Dela Cruz, Jez (Jez)',
                'emp_no' => '12693',
                'level' => 'Manager',
                'department' => 'FIN',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 42,
                'is_active' => true,
                'firstname' => 'Lady Fatima',
                'lastname' => 'Ocampo',
                'nickname' => 'Lady',
                'name' => 'Lady Ocampo',
                'position_title' => 'Assistant Treasury Manager',
                'reporting' => 'Manalastas, Leah (Leah)',
                'emp_no' => '15578',
                'level' => 'Manager',
                'department' => 'FIN',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 42,
                'is_active' => true,
                'firstname' => 'Abegail',
                'lastname' => 'Dela Peña',
                'nickname' => 'Abby',
                'name' => 'Abby Dela Peña',
                'position_title' => 'Treasury Officer',
                'reporting' => 'Manalastas, Leah (Leah)',
                'emp_no' => '19855',
                'level' => 'Supervisor / Officer',
                'department' => 'FIN',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 42,
                'is_active' => true,
                'firstname' => 'Aerielle Mae',
                'lastname' => 'Capaycapay',
                'nickname' => 'Aerielle',
                'name' => 'Aerielle Capaycapay',
                'position_title' => 'Treasury Officer',
                'reporting' => 'Manalastas, Leah (Leah)',
                'emp_no' => '32978',
                'level' => 'Supervisor / Officer',
                'department' => 'FIN',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 36,
                'is_active' => true,
                'firstname' => 'Rolando',
                'lastname' => 'Bondoy',
                'nickname' => 'Rolli',
                'name' => 'Rolli Bondoy',
                'position_title' => 'AVP, Head of Investor Relations & Comptrollership',
                'reporting' => 'Dela Cruz, Jez (Jez)',
                'emp_no' => '12899',
                'level' => 'Executive',
                'department' => 'FIN',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 46,
                'is_active' => true,
                'firstname' => 'Jesiree Anne',
                'lastname' => 'Chavez',
                'nickname' => 'Jes',
                'name' => 'Jes Chavez',
                'position_title' => 'Corporate Comptroller',
                'reporting' => 'Bondoy, Rolando (Rolli)',
                'emp_no' => '19033',
                'level' => 'Manager',
                'department' => 'FIN',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 46,
                'is_active' => true,
                'firstname' => 'Michelle',
                'lastname' => 'Fernandez',
                'nickname' => 'Mich',
                'name' => 'Mich Fernandez',
                'position_title' => 'Financial Reporting Officer',
                'reporting' => 'Bondoy, Rolando (Rolli)',
                'emp_no' => '105554',
                'level' => 'Supervisor / Officer',
                'department' => 'FIN',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 46,
                'is_active' => true,
                'firstname' => 'Benedict',
                'lastname' => 'Boac',
                'nickname' => 'Emp',
                'name' => 'Emp Boac',
                'position_title' => 'Financial Reporting Officer',
                'reporting' => 'Bondoy, Rolando (Rolli)',
                'emp_no' => '106045',
                'level' => 'Supervisor / Officer',
                'department' => 'FIN',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 46,
                'is_active' => true,
                'firstname' => 'Franscoise',
                'lastname' => 'Enriquez',
                'nickname' => 'Frans',
                'name' => 'Frans Enriquez',
                'position_title' => 'Accounting Assistant',
                'reporting' => 'Bondoy, Rolando (Rolli)',
                'emp_no' => '20388',
                'level' => 'Rank & File',
                'department' => 'FIN',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 46,
                'is_active' => false,
                'firstname' => 'Employee',
                'lastname' => 'Vacant',
                'nickname' => 'Emp',
                'name' => 'Vacant, Employee (Emp)',
                'position_title' => 'Accounting Assistant',
                'reporting' => 'Bondoy, Rolando (Rolli)',
                'emp_no' => '0',
                'level' => 'Rank & File',
                'department' => 'FIN',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 46,
                'is_active' => true,
                'firstname' => 'Jamie',
                'lastname' => 'Saberon',
                'nickname' => 'Jamie',
                'name' => 'Jamie Saberon',
                'position_title' => 'Investor Relations Officer',
                'reporting' => 'Bondoy, Rolando (Rolli)',
                'emp_no' => '20251',
                'level' => 'Supervisor / Officer',
                'department' => 'FIN',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 1,
                'is_active' => true,
                'firstname' => 'Maria Belinda',
                'lastname' => 'Morales',
                'nickname' => 'Beth',
                'name' => 'Beth Morales',
                'position_title' => 'Chief Human Resources Officer',
                'reporting' => 'Saavedra, Edgar (Ed)',
                'emp_no' => '15466',
                'level' => 'Executive',
                'department' => 'HRD',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 53,
                'is_active' => true,
                'firstname' => 'Jovie Milagros',
                'lastname' => 'Silvestre',
                'nickname' => 'Jovie',
                'name' => 'Jovie Silvestre',
                'position_title' => 'Talent Acquisition & HR Operations Head',
                'reporting' => 'Morales, Maria Belinda (Beth)',
                'emp_no' => '18892',
                'level' => 'Manager',
                'department' => 'HRD',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 54,
                'is_active' => true,
                'firstname' => 'Winnie',
                'lastname' => 'Matias',
                'nickname' => 'Wins',
                'name' => 'Wins Matias',
                'position_title' => 'Executive Compensation & Talent Acquisition Officer',
                'reporting' => 'Silvestre, Jovie Milagros (Jovie)',
                'emp_no' => '14699',
                'level' => 'Supervisor / Officer',
                'department' => 'HRD',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 54,
                'is_active' => true,
                'firstname' => 'Jomar',
                'lastname' => 'Buenaflor',
                'nickname' => 'Joms',
                'name' => 'Joms Buenaflor',
                'position_title' => 'Payroll & Benefits Assistant',
                'reporting' => 'Silvestre, Jovie Milagros (Jovie)',
                'emp_no' => '39724',
                'level' => 'Rank & File',
                'department' => 'HRD',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 54,
                'is_active' => true,
                'firstname' => 'Angellica Rose',
                'lastname' => 'Villavilla',
                'nickname' => 'Angel',
                'name' => 'Angel Villavilla',
                'position_title' => 'HR Generalist',
                'reporting' => 'Silvestre, Jovie Milagros (Jovie)',
                'emp_no' => '106000',
                'level' => 'Rank & File',
                'department' => 'HRD',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 53,
                'is_active' => true,
                'firstname' => 'Jayson',
                'lastname' => 'Barte',
                'nickname' => 'Jayson',
                'name' => 'Jayson Barte',
                'position_title' => 'HCM Analyst',
                'reporting' => 'Morales, Maria Belinda (Beth)',
                'emp_no' => '16847',
                'level' => 'Supervisor / Officer',
                'department' => 'HRD',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 53,
                'is_active' => true,
                'firstname' => 'Pryncess Hyacinth',
                'lastname' => 'Esguerra',
                'nickname' => 'Pryncess',
                'name' => 'Pryncess Esguerra',
                'position_title' => 'Learning & Engagement Head',
                'reporting' => 'Morales, Maria Belinda (Beth)',
                'emp_no' => '20024',
                'level' => 'Manager',
                'department' => 'HRD',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 59,
                'is_active' => true,
                'firstname' => 'Timothy',
                'lastname' => 'Osma',
                'nickname' => 'Tim',
                'name' => 'Tim Osma',
                'position_title' => 'Learning & Engagement Officer',
                'reporting' => 'Esguerra, Pryncess Hyacinth (Pryncess)',
                'emp_no' => '19224',
                'level' => 'Supervisor / Officer',
                'department' => 'HRD',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 53,
                'is_active' => true,
                'firstname' => 'John Patrick',
                'lastname' => 'Garcia',
                'nickname' => 'Pat',
                'name' => 'Pat Garcia',
                'position_title' => 'Talent Management & Total Rewards Officer',
                'reporting' => 'Morales, Maria Belinda (Beth)',
                'emp_no' => '19710',
                'level' => 'Supervisor / Officer',
                'department' => 'HRD',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 53,
                'is_active' => true,
                'firstname' => 'Nigel Bryant',
                'lastname' => 'Evangelista',
                'nickname' => 'Nigel',
                'name' => 'Nigel Evangelista',
                'position_title' => 'Assistant Organizational Development Manager',
                'reporting' => 'Morales, Maria Belinda (Beth)',
                'emp_no' => '18820',
                'level' => 'Manager',
                'department' => 'HRD',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 53,
                'is_active' => true,
                'firstname' => 'Kristina Mae',
                'lastname' => 'Inciong',
                'nickname' => 'Tin',
                'name' => 'Tin Inciong',
                'position_title' => 'Assistant Admin & Purchasing Manager',
                'reporting' => 'Morales, Maria Belinda (Beth)',
                'emp_no' => '18253',
                'level' => 'Manager',
                'department' => 'HRD',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 63,
                'is_active' => true,
                'firstname' => 'Ivana Jane',
                'lastname' => 'Borbon',
                'nickname' => 'Jing',
                'name' => 'Jing Borbon',
                'position_title' => 'Admin & Purchasing Assistant',
                'reporting' => 'Inciong, Kristina Mae (Tin)',
                'emp_no' => '57698',
                'level' => 'Rank & File',
                'department' => 'HRD',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 63,
                'is_active' => true,
                'firstname' => 'John Paul',
                'lastname' => 'Magdua',
                'nickname' => 'Paul',
                'name' => 'Paul Magdua',
                'position_title' => 'Driver',
                'reporting' => 'Inciong, Kristina Mae (Tin)',
                'emp_no' => '12275',
                'level' => 'Rank & File',
                'department' => 'HRD',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 63,
                'is_active' => true,
                'firstname' => 'Rusky',
                'lastname' => 'Ferrer',
                'nickname' => 'Rusky',
                'name' => 'Rusky Ferrer',
                'position_title' => 'Messenger',
                'reporting' => 'Inciong, Kristina Mae (Tin)',
                'emp_no' => '879',
                'level' => 'Rank & File',
                'department' => 'HRD',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 63,
                'is_active' => true,
                'firstname' => 'Phillip',
                'lastname' => 'Clavio',
                'nickname' => 'Philip',
                'name' => 'Philip Clavio',
                'position_title' => 'Messenger',
                'reporting' => 'Inciong, Kristina Mae (Tin)',
                'emp_no' => '17188',
                'level' => 'Rank & File',
                'department' => 'HRD',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 1,
                'is_active' => true,
                'firstname' => 'Raymund Jay',
                'lastname' => 'Gomez',
                'nickname' => 'Bom',
                'name' => 'Bom Gomez',
                'position_title' => 'Chief Legal Officer',
                'reporting' => 'Saavedra, Edgar (Ed)',
                'emp_no' => '12197',
                'level' => 'Executive',
                'department' => 'LEG',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 68,
                'is_active' => true,
                'firstname' => 'Ricky Boy',
                'lastname' => 'Cabatu',
                'nickname' => 'Ricky',
                'name' => 'Ricky Cabatu',
                'position_title' => 'Senior Legal Counsel, Corp Secretarial & Compliance',
                'reporting' => 'Gomez, Raymund Jay (Bom)',
                'emp_no' => '47467',
                'level' => 'Manager',
                'department' => 'LEG',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 68,
                'is_active' => true,
                'firstname' => 'Kristine Aira',
                'lastname' => 'Inao',
                'nickname' => 'Aira',
                'name' => 'Aira Inao',
                'position_title' => 'Paralegal',
                'reporting' => 'Gomez, Raymund Jay (Bom)',
                'emp_no' => '13759',
                'level' => 'Rank & File',
                'department' => 'LEG',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 68,
                'is_active' => true,
                'firstname' => 'Nica Marsha',
                'lastname' => 'Gasapo',
                'nickname' => 'Nica',
                'name' => 'Nica Gasapo',
                'position_title' => 'Legal Counsel',
                'reporting' => 'Gomez, Raymund Jay (Bom)',
                'emp_no' => '53152',
                'level' => 'Manager',
                'department' => 'LEG',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 71,
                'is_active' => true,
                'firstname' => 'Neil Kirby',
                'lastname' => 'Ada',
                'nickname' => 'Kirby',
                'name' => 'Kirby Ada',
                'position_title' => 'Associate Legal Counsel',
                'reporting' => 'Gasapo, Nica Marsha (Nica)',
                'emp_no' => '19823',
                'level' => 'Manager',
                'department' => 'LEG',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 71,
                'is_active' => true,
                'firstname' => 'Laila',
                'lastname' => 'Antoniano',
                'nickname' => 'Lei',
                'name' => 'Lei Gasapo',
                'position_title' => 'Paralegal',
                'reporting' => 'Gasapo, Nica Marsha (Nica)',
                'emp_no' => '61251',
                'level' => 'Rank & File',
                'department' => 'LEG',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 71,
                'is_active' => true,
                'firstname' => 'Giancharlie',
                'lastname' => 'Go',
                'nickname' => 'Giggy',
                'name' => 'Giggy Go',
                'position_title' => 'Senior Legal Counsel',
                'reporting' => 'Gasapo, Nica Marsha (Nica)',
                'emp_no' => '20076',
                'level' => 'Manager',
                'department' => 'LEG',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 74,
                'is_active' => true,
                'firstname' => 'Janelle Caryn',
                'lastname' => 'Dela Cruz',
                'nickname' => 'Janelle',
                'name' => 'Janelle Dela Cruz',
                'position_title' => 'Associate Legal Counsel',
                'reporting' => 'Go, Giancharlie (Giggy)',
                'emp_no' => '19894',
                'level' => 'Manager',
                'department' => 'LEG',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 68,
                'is_active' => true,
                'firstname' => 'Niño Jovit',
                'lastname' => 'Jimenez',
                'nickname' => 'Nino',
                'name' => 'Nino Jimenez',
                'position_title' => 'Corporate Regulatory Officer',
                'reporting' => 'Gomez, Raymund Jay (Bom)',
                'emp_no' => '12895',
                'level' => 'Supervisor / Officer',
                'department' => 'LEG',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE'
            ],
            [
                'pid' => 1,
                'is_active' => true,
                'firstname' => 'Teresa',
                'lastname' => 'Saavedra',
                'nickname' => 'Tata',
                'name' => 'Tata Saavedra',
                'position_title' => 'President',
                'reporting' => 'Saavedra, Edgar (Ed)',
                'emp_no' => '19162',
                'level' => 'Executive',
                'department' => 'FDN',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE FDN'
            ],
            [
                'pid' => 77,
                'is_active' => true,
                'firstname' => 'Carmela',
                'lastname' => 'Castro',
                'nickname' => 'Mia',
                'name' => 'Mia Castro',
                'position_title' => 'Executive Director',
                'reporting' => 'Saavedra, Teresa (Tata)',
                'emp_no' => '20083',
                'level' => 'Manager',
                'department' => 'FDN',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE FDN'
            ],
            [
                'pid' => 77,
                'is_active' => true,
                'firstname' => 'Claudine',
                'lastname' => 'Manuel',
                'nickname' => 'Claud',
                'name' => 'Claud Manuel ',
                'position_title' => 'Assistant Program Manager',
                'reporting' => 'Saavedra, Teresa (Tata)',
                'emp_no' => '27936',
                'level' => 'Manager',
                'department' => 'FDN',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE FDN'
            ],
            [
                'pid' => 79,
                'is_active' => true,
                'firstname' => 'Saleah Joy',
                'lastname' => 'Uclusin',
                'nickname' => 'Saleah',
                'name' => 'Saleah Uclusin',
                'position_title' => 'Program Officer',
                'reporting' => 'Manuel, Claudine (Claud)',
                'emp_no' => '18133',
                'level' => 'Supervisor / Officer',
                'department' => 'FDN',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE FDN'
            ],
            [
                'pid' => 79,
                'is_active' => true,
                'firstname' => 'Julia Izah',
                'lastname' => 'Agida',
                'nickname' => 'Julia',
                'name' => 'Uclusin Agida',
                'position_title' => 'Program Officer',
                'reporting' => 'Manuel, Claudine (Claud)',
                'emp_no' => '82634',
                'level' => 'Supervisor / Officer',
                'department' => 'FDN',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE FDN'
            ],
            [
                'pid' => 77,
                'is_active' => true,
                'firstname' => 'Jesiree Anne',
                'lastname' => 'Chavez',
                'nickname' => 'Jes',
                'name' => 'Jes Chavez',
                'position_title' => 'Finance & Admin Officer',
                'reporting' => 'Saavedra, Teresa (Tata)',
                'emp_no' => '19033',
                'level' => 'Supervisor / Officer',
                'department' => 'FDN',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE FDN'
            ],
            [
                'pid' => 77,
                'is_active' => true,
                'firstname' => 'Jimmy',
                'lastname' => 'Alberca',
                'nickname' => 'Jimmy',
                'name' => 'Jimmy Alberca',
                'position_title' => 'Driver',
                'reporting' => 'Saavedra, Teresa (Tata)',
                'emp_no' => '105636',
                'level' => 'Rank & File',
                'department' => 'FDN',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE FDN'
            ],
        ];

        foreach ($data as $item) {
            \App\Models\OrgStructure::create($item);
        }
    }

}
