<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OrgStructureSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'pid' => null,
                'is_active' => true,
                'firstname' => 'Edgar',
                'lastname' => 'Saavedra',
                'nickname' => 'Ed',
                'name' => 'Edgar Saavedra',
                'email' => 'edgar@megawide.com.ph',
                'position_title' => 'Chairman & CEO',
                'reporting' => 'Not Applicable',
                'emp_no' => '1',
                'level' => 'Executive',
                'department' => 'OCEO',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/esa.jpg'
            ],
            [
                'pid' => 1,
                'is_active' => true,
                'firstname' => 'Bernice Jillian',
                'lastname' => 'Hu',
                'nickname' => 'Bern',
                'name' => 'Bernice Jillian Hu',
                'email' => 'bjhu@megawide.com.ph',
                'position_title' => 'Management Associate',
                'reporting' => 'Saavedra, Edgar (Ed)',
                'emp_no' => '68074',
                'level' => 'Manager',
                'department' => 'OCEO',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/bern.png'
            ],
            [
                'pid' => 1,
                'is_active' => false,
                'firstname' => 'Vacant',
                'lastname' => 'Vacant',
                'nickname' => 'Emp',
                'name' => 'Employee',
                'email' => '',
                'position_title' => 'Management Associate',
                'reporting' => 'Saavedra, Edgar (Ed)',
                'emp_no' => '0',
                'level' => 'Manager',
                'department' => 'OCEO',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => null
            ],
            [
                'pid' => 1,
                'is_active' => false,
                'firstname' => 'Vacant',
                'lastname' => 'Vacant',
                'nickname' => 'Emp',
                'name' => 'Employee',
                'email' => '',
                'position_title' => 'Management Associate',
                'reporting' => 'Saavedra, Edgar (Ed)',
                'emp_no' => '0',
                'level' => 'Manager',
                'department' => 'OCEO',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => null
            ],
            [
                'pid' => 2,
                'is_active' => true,
                'firstname' => 'Jellica Aine',
                'lastname' => 'Santos',
                'nickname' => 'Jelli',
                'name' => 'Jellica Aine Santos',
                'email' => 'jasantos2@megawide.com.ph',
                'position_title' => 'Management Trainee',
                'reporting' => 'Hu, Bernice Jillian (Bern)',
                'emp_no' => '20589',
                'level' => 'Supervisor / Officer',
                'department' => 'OCEO',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/jelli.png'
            ],
            [
                'pid' => 2,
                'is_active' => true,
                'firstname' => 'Joland Abby',
                'lastname' => 'Batiancila',
                'nickname' => 'Abby',
                'name' => 'Joland Abby Batiancila',
                'email' => 'jabatiancila@megawide.com.ph',
                'position_title' => 'Management Trainee',
                'reporting' => 'Hu, Bernice Jillian (Bern)',
                'emp_no' => '79792',
                'level' => 'Supervisor / Officer',
                'department' => 'OCEO',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/abby.png'
            ],
            [
                'pid' => 2,
                'is_active' => true,
                'firstname' => 'Rafael',
                'lastname' => 'Saavedra',
                'nickname' => 'Raf',
                'name' => 'Rafael Saavedra',
                'email' => 'rafael@megawide.com.ph',
                'position_title' => 'Management Trainee',
                'reporting' => 'Hu, Bernice Jillian (Bern)',
                'emp_no' => '105924',
                'level' => 'Supervisor / Officer',
                'department' => 'OCEO',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/raf.png'
            ],
            [
                'pid' => 2,
                'is_active' => true,
                'firstname' => 'Carvey Carrick',
                'lastname' => 'Chan',
                'nickname' => 'Carvey',
                'name' => 'Carvey Carrick Chan',
                'email' => 'cchan@megawide.com.ph',
                'position_title' => 'Management Trainee',
                'reporting' => 'Hu, Bernice Jillian (Bern)',
                'emp_no' => '106024',
                'level' => 'Supervisor / Officer',
                'department' => 'OCEO',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/carvey.png'
            ],
            [
                'pid' => 2,
                'is_active' => true,
                'firstname' => 'Melissa',
                'lastname' => 'Salilican',
                'nickname' => 'Myles',
                'name' => 'Melissa Salilican',
                'email' => 'msalilican@megawide.com.ph',
                'position_title' => 'Facilities Management Officer',
                'reporting' => 'Saavedra, Edgar (Ed)',
                'emp_no' => '927',
                'level' => 'Supervisor / Officer',
                'department' => 'OCEO',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/myles.png'
            ],
            [
                'pid' => 2,
                'is_active' => true,
                'firstname' => 'Leo Pacholo',
                'lastname' => 'Mago',
                'nickname' => 'Lei',
                'name' => 'Leo Pacholo Mago',
                'email' => 'lmago@megawide.com.ph',
                'position_title' => 'Enterprise Applications Manager',
                'reporting' => 'Saavedra, Edgar (Ed)',
                'emp_no' => '28930',
                'level' => 'Manager',
                'department' => 'OCEO',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/lei.png'
            ],
            [
                'pid' => 1,
                'is_active' => true,
                'firstname' => 'Christopher',
                'lastname' => 'Nadayag',
                'nickname' => 'Chris',
                'name' => 'Christopher Nadayag',
                'email' => 'cnadayag@megawide.com.ph',
                'position_title' => 'AVP, Head of Internal Audit',
                'reporting' => 'Saavedra, Edgar (Ed)',
                'emp_no' => '726',
                'level' => 'Executive',
                'department' => 'OCHR',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/chris.png'
            ],
            [
                'pid' => 11,
                'is_active' => true,
                'firstname' => 'Ricci Angelo',
                'lastname' => 'Pasamba',
                'nickname' => 'Ricci',
                'name' => 'Ricci Angelo Pasamba',
                'email' => 'rpasamba@megawide.com.ph',
                'position_title' => 'Internal Audit Officer',
                'reporting' => 'Nadayag, Christopher (Chris)',
                'emp_no' => '58622',
                'level' => 'Supervisor / Officer',
                'department' => 'OCHR',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/ricci.png'
            ],
            [
                'pid' => 11,
                'is_active' => true,
                'firstname' => 'Errol Benedict',
                'lastname' => 'Purcia',
                'nickname' => 'Errol',
                'name' => 'Errol Benedict Purcia',
                'email' => 'bpurcia@megawide.com.ph',
                'position_title' => 'Internal Audit Officer',
                'reporting' => 'Nadayag, Christopher (Chris)',
                'emp_no' => '83628',
                'level' => 'Supervisor / Officer',
                'department' => 'OCHR',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/errol.png'
            ],
            [
                'pid' => 2,
                'is_active' => true,
                'firstname' => 'Mark Joseph',
                'lastname' => 'Druja',
                'nickname' => 'MJ',
                'name' => 'Mark Joseph Druja',
                'email' => 'mjdruja@gmail.com',
                'position_title' => 'Driver',
                'reporting' => 'Edgar Saavedra',
                'emp_no' => '1024',
                'level' => 'Rank & File',
                'department' => 'OCEO',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/mj.png'
            ],
            [
                'pid' => 14,
                'is_active' => true,
                'firstname' => 'Ryan',
                'lastname' => 'Viray',
                'nickname' => 'Ryan',
                'name' => 'Ryan Viray',
                'email' => 'Ryanviray25@gmail.com',
                'position_title' => 'Driver',
                'reporting' => 'Edgar Saavedra',
                'emp_no' => '1771',
                'level' => 'Rank & File',
                'department' => 'OCEO',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/ryan.png'
            ],
            [
                'pid' => 14,
                'is_active' => true,
                'firstname' => 'Nelson',
                'lastname' => 'Clerigo',
                'nickname' => 'Nelson',
                'name' => 'Nelson Clerigo',
                'email' => 'marcclerigo2@gmail.com',
                'position_title' => 'VIP Security',
                'reporting' => 'Edgar Saavedra',
                'emp_no' => '17807',
                'level' => 'Rank & File',
                'department' => 'OCEO',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/nelson.png'
            ],
            [
                'pid' => 14,
                'is_active' => true,
                'firstname' => 'Danny',
                'lastname' => 'Austero',
                'nickname' => 'Danny',
                'name' => 'Danny Austero',
                'email' => 'austerodanny1@gmail.com',
                'position_title' => 'VIP Security',
                'reporting' => 'Edgar Saavedra',
                'emp_no' => '24173',
                'level' => 'Rank & File',
                'department' => 'OCEO',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/danny.png'
            ],
            [
                'pid' => 14,
                'is_active' => true,
                'firstname' => 'Arnel',
                'lastname' => 'Estacoja',
                'nickname' => 'Arnel',
                'name' => 'Arnel Estacoja',
                'email' => 'estacojaa@gmail.com',
                'position_title' => 'VIP Security',
                'reporting' => 'Edgar Saavedra',
                'emp_no' => '33688',
                'level' => 'Rank & File',
                'department' => 'OCEO',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/arnel.png'
            ],
            [
                'pid' => 1,
                'is_active' => true,
                'firstname' => 'Jaime Raphael',
                'lastname' => 'Feliciano',
                'nickname' => 'Jim',
                'name' => 'Jaime Raphael Feliciano',
                'email' => 'jfeliciano@megawide.com.ph',
                'position_title' => 'Chief Business Development Officer',
                'reporting' => 'Edgar Saavedra',
                'emp_no' => '7384',
                'level' => 'Executive',
                'department' => 'BDV',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => null
            ],
            [
                'pid' => 19,
                'is_active' => true,
                'firstname' => 'Stephanie Ann',
                'lastname' => 'Soon',
                'nickname' => 'Steph',
                'name' => 'Stephanie Ann Soon',
                'email' => 'ssoon@megawide.com.ph',
                'position_title' => 'Business Development Director',
                'reporting' => 'Jaime Raphael Feliciano',
                'emp_no' => '19307',
                'level' => 'Manager',
                'department' => 'BDV',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/steph.png'
            ],
            [
                'pid' => 20,
                'is_active' => true,
                'firstname' => 'Danielle Marie',
                'lastname' => 'Feliciano',
                'nickname' => 'Danes',
                'name' => 'Danielle Marie Feliciano',
                'email' => 'dmfeliciano@megawide.com.ph',
                'position_title' => 'Business Development Manager',
                'reporting' => 'Stephanie Ann Soon',
                'emp_no' => '73188',
                'level' => 'Manager',
                'department' => 'BDV',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/danes.png'
            ],
            [
                'pid' => 20,
                'is_active' => true,
                'firstname' => 'Jasmin',
                'lastname' => 'Fernandez',
                'nickname' => 'Jas',
                'name' => 'Jasmin Fernandez',
                'email' => 'jfernandez@megawide.com.ph',
                'position_title' => 'Assistant Business Development Manager',
                'reporting' => 'Stephanie Ann Soon',
                'emp_no' => '19377',
                'level' => 'Manager',
                'department' => 'BDV',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/jas.png'
            ],
            [
                'pid' => 20,
                'is_active' => true,
                'firstname' => 'Adrian Paul',
                'lastname' => 'Flores',
                'nickname' => 'Adrian',
                'name' => 'Adrian Paul Flores',
                'email' => 'apflores@megawide.com.ph',
                'position_title' => 'Business Development Officer',
                'reporting' => 'Stephanie Ann Soon',
                'emp_no' => '105894',
                'level' => 'Supervisor / Officer',
                'department' => 'BDV',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/adrian.png'
            ],
            [
                'pid' => 20,
                'is_active' => true,
                'firstname' => 'Rhiz Kathleen',
                'lastname' => 'Contreras',
                'nickname' => 'Kath',
                'name' => 'Rhiz Kathleen Contreras',
                'email' => 'rkcontreras@megawide.com.ph',
                'position_title' => 'Senior Business Development Assistant',
                'reporting' => 'Stephanie Ann Soon',
                'emp_no' => '17334',
                'level' => 'Rank & File',
                'department' => 'BDV',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/kath.png'
            ],
            [
                'pid' => 19,
                'is_active' => true,
                'firstname' => 'Milestill',
                'lastname' => 'Young',
                'nickname' => 'Miles',
                'name' => 'Milestill Young',
                'email' => 'myoung@megawide.com.ph',
                'position_title' => 'Business Development Director',
                'reporting' => 'Jaime Raphael Feliciano',
                'emp_no' => '5283',
                'level' => 'Manager',
                'department' => 'TDV',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/miles.png'
            ],
            [
                'pid' => 25,
                'is_active' => true,
                'firstname' => 'James Matthew',
                'lastname' => 'Jaramillo',
                'nickname' => 'Matt',
                'name' => 'James Matthew Jaramillo',
                'email' => 'jmjaramillo@megawide.com.ph',
                'position_title' => 'Business Development Officer',
                'reporting' => 'Milestill Young',
                'emp_no' => '19998',
                'level' => 'Supervisor / Officer',
                'department' => 'TDV',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/matt.png'
            ],
            [
                'pid' => 25,
                'is_active' => true,
                'firstname' => 'Gyan Louie',
                'lastname' => 'Gloriani',
                'nickname' => 'Gyan',
                'name' => 'Gyan Louie Gloriani',
                'email' => 'ggloriani@megawide.com.ph',
                'position_title' => 'Business Development Officer',
                'reporting' => 'Milestill Young',
                'emp_no' => '21542',
                'level' => 'Supervisor / Officer',
                'department' => 'TDV',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/gyan.png'
            ],
            [
                'pid' => 25,
                'is_active' => true,
                'firstname' => 'Fernando Miguel',
                'lastname' => 'Lozano',
                'nickname' => 'Lozi',
                'name' => 'Fernando Miguel Lozano',
                'email' => 'fmlozano@megawide.com.ph',
                'position_title' => 'Business Development Officer',
                'reporting' => 'Milestill Young',
                'emp_no' => '21613',
                'level' => 'Supervisor / Officer',
                'department' => 'TDV',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/lozi.png'
            ],
            [
                'pid' => 1,
                'is_active' => true,
                'firstname' => 'Manuel Louie',
                'lastname' => 'Ferrer',
                'nickname' => 'LF',
                'name' => 'Manuel Louie Ferrer',
                'email' => 'louie@megawide.com.ph',
                'position_title' => 'Chief Corporate Communications, Affairs & Branding Officer',
                'reporting' => 'Edgar Saavedra',
                'emp_no' => '1346',
                'level' => 'Executive',
                'department' => 'CCAB',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => null
            ],
            [
                'pid' => 29,
                'is_active' => true,
                'firstname' => 'Nierra Jobel',
                'lastname' => 'Azogue',
                'nickname' => 'Nierra',
                'name' => 'Nierra Jobel Azogue',
                'email' => 'njazogue@megawide.com.ph',
                'position_title' => 'Executive Assistant',
                'reporting' => 'Manuel Louie Ferrer',
                'emp_no' => '19251',
                'level' => 'Supervisor / Officer',
                'department' => 'CCAB',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/nierra.png'

            ],
            [
                'pid' => 29,
                'is_active' => true,
                'firstname' => 'Ericson',
                'lastname' => 'Benitez',
                'nickname' => 'Ericson',
                'name' => 'Ericson Benitez',
                'email' => 'ebenitez@megawide.com.ph',
                'position_title' => 'Driver',
                'reporting' => 'Manuel Louie Ferrer',
                'emp_no' => '3996',
                'level' => 'Rank & File',
                'department' => 'CCAB',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => null
            ],
            [
                'pid' => 29,
                'is_active' => false,
                'firstname' => 'Vacant',
                'lastname' => 'Vacant',
                'nickname' => 'Emp',
                'name' => 'Employee',
                'email' => '',
                'position_title' => 'Corporate Communications and Branding Manager',
                'reporting' => 'Manuel Louie Ferrer',
                'emp_no' => '0',
                'level' => 'Manager',
                'department' => 'CCAB',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => null
            ],
            [
                'pid' => 29,
                'is_active' => true,
                'firstname' => 'Timothy Alexander',
                'lastname' => 'Glova',
                'nickname' => 'Tim',
                'name' => 'Timothy Alexander Glova',
                'email' => 'taglova@megawide.com.ph',
                'position_title' => 'Stakeholder Relations Officer / Management Associate',
                'reporting' => 'Manuel Louie Ferrer',
                'emp_no' => '19130',
                'level' => 'Supervisor / Officer',
                'department' => 'CCAB',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/tim.png'
            ],
            [
                'pid' => 1,
                'is_active' => true,
                'firstname' => 'Jez',
                'lastname' => 'Dela Cruz',
                'nickname' => 'Jez',
                'name' => 'Jez Dela Cruz',
                'email' => 'jgdelacruz@megawide.com.ph',
                'position_title' => 'Group Chief Finance Officer',
                'reporting' => 'Edgar Saavedra',
                'emp_no' => '13067',
                'level' => 'Executive',
                'department' => 'FIN',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/jez.png'
            ],
            [
                'pid' => 34,
                'is_active' => true,
                'firstname' => 'Reza Marie',
                'lastname' => 'De Guzman',
                'nickname' => 'Reza',
                'name' => 'Reza Marie De Guzman',
                'email' => 'rdeguzman@megawide.com.ph',
                'position_title' => 'Executive Assistant',
                'reporting' => 'Jez Dela Cruz',
                'emp_no' => '15682',
                'level' => 'Supervisor / Officer',
                'department' => 'FIN',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/reza.png'
            ],
            [
                'pid' => 35,
                'is_active' => true,
                'firstname' => 'John Reaner',
                'lastname' => 'Nocum',
                'nickname' => 'Rein',
                'name' => 'John Reaner Nocum',
                'email' => 'rnocum@megawide.com.ph',
                'position_title' => 'AVP, Head of Corporate Finance & Planning',
                'reporting' => 'Jez Dela Cruz',
                'emp_no' => '13216',
                'level' => 'Executive',
                'department' => 'FIN',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/rein.png'
            ],
            [
                'pid' => 36,
                'is_active' => true,
                'firstname' => 'Stephanie',
                'lastname' => 'Chua',
                'nickname' => 'Steph',
                'name' => 'Stephanie Chua',
                'email' => 'schua@megawide.com.ph',
                'position_title' => 'Senior Corporate Finance & Planning Manager',
                'reporting' => 'John Reaner Nocum',
                'emp_no' => '18884',
                'level' => 'Manager',
                'department' => 'FIN',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/stephchua.png'
            ],
            [
                'pid' => 36,
                'is_active' => true,
                'firstname' => 'Jose Enrique',
                'lastname' => 'Sayon',
                'nickname' => 'Nico',
                'name' => 'Jose Enrique Sayon',
                'email' => 'jesayon@megawide.com.ph',
                'position_title' => 'Assistant Corporate Finance & Planning Manager',
                'reporting' => 'John Reaner Nocum',
                'emp_no' => '13819',
                'level' => 'Manager',
                'department' => 'FIN',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/nico.png'
            ],
            [
                'pid' => 36,
                'is_active' => true,
                'firstname' => 'Eric Rian',
                'lastname' => 'Lomibao',
                'nickname' => 'Eric',
                'name' => 'Eric Rian Lomibao',
                'email' => 'erlomibao@megawide.com.ph',
                'position_title' => 'Assistant Corporate Finance & Planning Manager',
                'reporting' => 'John Reaner Nocum',
                'emp_no' => '19114',
                'level' => 'Manager',
                'department' => 'FIN',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/eric.png'
            ],
            [
                'pid' => 34,
                'is_active' => true,
                'firstname' => 'Leah',
                'lastname' => 'Manalastas',
                'nickname' => 'Leah',
                'name' => 'Leah Manalastas',
                'email' => 'lmanalastas@megawide.com.ph',
                'position_title' => 'Treasury Head',
                'reporting' => 'Jez Dela Cruz',
                'emp_no' => '12693',
                'level' => 'Manager',
                'department' => 'FIN',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/leah.png'
            ],
            [
                'pid' => 40,
                'is_active' => true,
                'firstname' => 'Lady Fatima',
                'lastname' => 'Ocampo',
                'nickname' => 'Lady',
                'name' => 'Lady Fatima Ocampo',
                'email' => 'lfocampo@megawide.com.ph',
                'position_title' => 'Assistant Treasury Manager',
                'reporting' => 'Leah Manalastas',
                'emp_no' => '15578',
                'level' => 'Manager',
                'department' => 'FIN',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/lady.png'
            ],
            [
                'pid' => 40,
                'is_active' => true,
                'firstname' => 'Abegail',
                'lastname' => 'Dela Peña',
                'nickname' => 'Abby',
                'name' => 'Abegail Dela Peña',
                'email' => 'adelapena@megawide.com.ph',
                'position_title' => 'Treasury Officer',
                'reporting' => 'Leah Manalastas',
                'emp_no' => '19855',
                'level' => 'Supervisor / Officer',
                'department' => 'FIN',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/abbydelapena.png'
            ],
            [
                'pid' => 40,
                'is_active' => true,
                'firstname' => 'Aerielle Mae',
                'lastname' => 'Capaycapay',
                'nickname' => 'Aerielle',
                'name' => 'Aerielle Mae Capaycapay',
                'email' => 'lfocampo@megawide.com.ph',
                'position_title' => 'Treasury Officer',
                'reporting' => 'Leah Manalastas',
                'emp_no' => '32978',
                'level' => 'Supervisor / Officer',
                'department' => 'FIN',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/aerielle.png'
            ],
            [
                'pid' => 34,
                'is_active' => true,
                'firstname' => 'Rolando',
                'lastname' => 'Bondoy',
                'nickname' => 'Rolli',
                'name' => 'Rolando Bondoy',
                'email' => 'rbondoy@megawide.com.ph',
                'position_title' => 'AVP, Head of Investor Relations & Comptrollership',
                'reporting' => 'Jez Dela Cruz',
                'emp_no' => '12899',
                'level' => 'Executive',
                'department' => 'FIN',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/rolli.png'
            ],
            [
                'pid' => 44,
                'is_active' => true,
                'firstname' => 'Jesiree Anne',
                'lastname' => 'Chavez',
                'nickname' => 'Jes',
                'name' => 'Jesiree Anne Chavez',
                'email' => 'jchavez@megawide.com.ph',
                'position_title' => 'Corporate Comptroller',
                'reporting' => 'Rolando Bondoy',
                'emp_no' => '19033',
                'level' => 'Manager',
                'department' => 'FIN',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/jes.png'
            ],
            [
                'pid' => 44,
                'is_active' => true,
                'firstname' => 'Michelle',
                'lastname' => 'Fernandez',
                'nickname' => 'Mich',
                'name' => 'Michelle Fernandez',
                'email' => 'mfernandez@megawide.com.ph',
                'position_title' => 'Financial Reporting Officer',
                'reporting' => 'Jesiree Anne Chavez',
                'emp_no' => '105554',
                'level' => 'Supervisor / Officer',
                'department' => 'FIN',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/mich.png'
            ],
            [
                'pid' => 44,
                'is_active' => true,
                'firstname' => 'Benedict',
                'lastname' => 'Boac',
                'nickname' => 'Emp',
                'name' => 'Benedict Boac',
                'email' => 'bboac@megawide.com.ph',
                'position_title' => 'Financial Reporting Officer',
                'reporting' => 'Jesiree Anne Chavez',
                'emp_no' => '106045',
                'level' => 'Supervisor / Officer',
                'department' => 'FIN',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/emp.png'
            ],
            [
                'pid' => 44,
                'is_active' => true,
                'firstname' => 'Franscoise',
                'lastname' => 'Enriquez',
                'nickname' => 'Frans',
                'name' => 'Franscoise Enriquez',
                'email' => 'fenriquez@megawide.com.ph',
                'position_title' => 'Accounting Assistant',
                'reporting' => 'Jesiree Anne Chavez',
                'emp_no' => '20388',
                'level' => 'Rank & File',
                'department' => 'FIN',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/frans.png'
            ],
            [
                'pid' => 44,
                'is_active' => false,
                'firstname' => 'Vacant',
                'lastname' => 'Vacant',
                'nickname' => 'Emp',
                'name' => 'Employee',
                'email' => '',
                'position_title' => 'Accounting Assistant',
                'reporting' => 'Jesiree Anne Chavez',
                'emp_no' => '0',
                'level' => 'Rank & File',
                'department' => 'FIN',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => null
            ],
            [
                'pid' => 44,
                'is_active' => true,
                'firstname' => 'Jamie',
                'lastname' => 'Saberon',
                'nickname' => 'Jamie',
                'name' => 'Jamie Saberon',
                'email' => 'jasaberon@megawide.com.ph',
                'position_title' => 'Investor Relations Officer',
                'reporting' => 'Bondoy, Rolando (Rolli)',
                'emp_no' => '20251',
                'level' => 'Supervisor / Officer',
                'department' => 'FIN',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/jamie.png'
            ],
            [
                'pid' => 1,
                'is_active' => true,
                'firstname' => 'Maria Belinda',
                'lastname' => 'Morales',
                'nickname' => 'Beth',
                'name' => 'Maria Belinda Morales',
                'email' => 'bmorales@megawide.com.ph',
                'position_title' => 'Chief Human Resources Officer',
                'reporting' => 'Edgar Saavedra',
                'emp_no' => '15466',
                'level' => 'Executive',
                'department' => 'HRD',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => null
            ],
            [
                'pid' => 51,
                'is_active' => true,
                'firstname' => 'Jovie Milagros',
                'lastname' => 'Silvestre',
                'nickname' => 'Jovie',
                'name' => 'Jovie Milagros Silvestre',
                'email' => 'jmsilvestre@megawide.com.ph',
                'position_title' => 'Talent Acquisition & HR Operations Head',
                'reporting' => 'Maria Belinda Morales',
                'emp_no' => '18892',
                'level' => 'Manager',
                'department' => 'HRD',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/jovie.png'
            ],
            [
                'pid' => 52,
                'is_active' => true,
                'firstname' => 'Winnie',
                'lastname' => 'Matias',
                'nickname' => 'Wins',
                'name' => 'Winnie Matias',
                'email' => 'wmatias@megawide.com.ph',
                'position_title' => 'HR Officer',
                'reporting' => 'Jovie Milagros Silvestre',
                'emp_no' => '14699',
                'level' => 'Supervisor / Officer',
                'department' => 'HRD',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/wins.png'
            ],
            [
                'pid' => 52,
                'is_active' => true,
                'firstname' => 'Jomar',
                'lastname' => 'Buenaflor',
                'nickname' => 'Joms',
                'name' => 'Jomar Buenaflor',
                'email' => 'jbuenaflor@megawide.com.ph',
                'position_title' => 'Payroll Specialist',
                'reporting' => 'Jovie Milagros Silvestre',
                'emp_no' => '39724',
                'level' => 'Rank & File',
                'department' => 'HRD',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/joms.png'
            ],
            [
                'pid' => 52,
                'is_active' => true,
                'firstname' => 'Angellica Rose',
                'lastname' => 'Villavilla',
                'nickname' => 'Angel',
                'name' => 'Angellica Rose Villavilla',
                'email' => 'arvillavilla@megawide.com.ph',
                'position_title' => 'Benefits Specialists',
                'reporting' => 'Jovie Milagros Silvestre',
                'emp_no' => '106000',
                'level' => 'Rank & File',
                'department' => 'HRD',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/angel.png'
            ],
            [
                'pid' => 51,
                'is_active' => true,
                'firstname' => 'Jayson',
                'lastname' => 'Barte',
                'nickname' => 'Jayson',
                'name' => 'Jayson Barte',
                'email' => 'jbarte@megawide.com.ph',
                'position_title' => 'HCM Analyst',
                'reporting' => 'Maria Belinda Morales',
                'emp_no' => '16847',
                'level' => 'Supervisor / Officer',
                'department' => 'HRD',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/jayson.png'
            ],
            [
                'pid' => 51,
                'is_active' => true,
                'firstname' => 'Pryncess Hyacinth',
                'lastname' => 'Esguerra',
                'nickname' => 'Pryncess',
                'name' => 'Pryncess Hyacinth Esguerra',
                'email' => 'phesguerra@megawide.com.ph',
                'position_title' => 'Learning & Engagement Head',
                'reporting' => 'Maria Belinda Morales',
                'emp_no' => '20024',
                'level' => 'Manager',
                'department' => 'HRD',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/pryncess.png'
            ],
            [
                'pid' => 57,
                'is_active' => true,
                'firstname' => 'Timothy',
                'lastname' => 'Osma',
                'nickname' => 'Tim',
                'name' => 'Timothy Osma',
                'email' => 'tosma@megawide.com.ph',
                'position_title' => 'Learning & Engagement Officer',
                'reporting' => 'Pryncess Hyacinth Esguerra',
                'emp_no' => '19224',
                'level' => 'Supervisor / Officer',
                'department' => 'HRD',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/timosma.png'
            ],
            [
                'pid' => 51,
                'is_active' => true,
                'firstname' => 'John Patrick',
                'lastname' => 'Garcia',
                'nickname' => 'Pat',
                'name' => 'John Patrick Garcia',
                'email' => 'jpgarcia@megawide.com.ph',
                'position_title' => 'Talent Management & Total Rewards Officer',
                'reporting' => 'Maria Belinda Morales',
                'emp_no' => '19710',
                'level' => 'Supervisor / Officer',
                'department' => 'HRD',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/pat.png'
            ],
            [
                'pid' => 51,
                'is_active' => true,
                'firstname' => 'Nigel Bryant',
                'lastname' => 'Evangelista',
                'nickname' => 'Nigel',
                'name' => 'Nigel Bryant Evangelista',
                'email' => 'nbevangelista@megawide.com.ph',
                'position_title' => 'Assistant Organizational Development Manager',
                'reporting' => 'Maria Belinda Morales',
                'emp_no' => '18820',
                'level' => 'Manager',
                'department' => 'HRD',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/nigel.png'
            ],
            [
                'pid' => 51,
                'is_active' => true,
                'firstname' => 'Kristina Mae',
                'lastname' => 'Inciong',
                'nickname' => 'Tin',
                'name' => 'Kristina Mae Inciong',
                'email' => 'kinciong@megawide.com.ph',
                'position_title' => 'Assistant Admin & Purchasing Manager',
                'reporting' => 'Maria Belinda Morales',
                'emp_no' => '18253',
                'level' => 'Manager',
                'department' => 'HRD',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/tin.png'
            ],
            [
                'pid' => 61,
                'is_active' => true,
                'firstname' => 'Ivana Jane',
                'lastname' => 'Borbon',
                'nickname' => 'Jing',
                'name' => 'Ivana Jane Borbon',
                'email' => 'iborbon@megawide.com.ph',
                'position_title' => 'Admin & Purchasing Assistant',
                'reporting' => 'Kristina Mae Inciong',
                'emp_no' => '57698',
                'level' => 'Rank & File',
                'department' => 'HRD',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => null
            ],
            [
                'pid' => 61,
                'is_active' => true,
                'firstname' => 'John Paul',
                'lastname' => 'Magdua',
                'nickname' => 'Paul',
                'name' => 'John Paul Magdua',
                'email' => 'jmagdua@megawide.com.ph',
                'position_title' => 'Driver',
                'reporting' => 'Kristina Mae Inciong',
                'emp_no' => '12275',
                'level' => 'Rank & File',
                'department' => 'HRD',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/paul.png'
            ],
            [
                'pid' => 61,
                'is_active' => true,
                'firstname' => 'Rusky',
                'lastname' => 'Ferrer',
                'nickname' => 'Rusky',
                'name' => 'Rusky Ferrer',
                'email' => 'ruskyferrer@gmail.com',
                'position_title' => 'Messenger',
                'reporting' => 'Kristina Mae Inciong',
                'emp_no' => '879',
                'level' => 'Rank & File',
                'department' => 'HRD',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => null
            ],
            [
                'pid' => 61,
                'is_active' => true,
                'firstname' => 'Phillip',
                'lastname' => 'Clavio',
                'nickname' => 'Philip',
                'name' => 'Phillip Clavio',
                'email' => 'Philipclavio2831@gmail.com',
                'position_title' => 'Messenger',
                'reporting' => 'Kristina Mae Inciong',
                'emp_no' => '17188',
                'level' => 'Rank & File',
                'department' => 'HRD',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/philip.png'
            ],
            [
                'pid' => 1,
                'is_active' => true,
                'firstname' => 'Raymund Jay',
                'lastname' => 'Gomez',
                'nickname' => 'Bom',
                'name' => 'Raymund Jay Gomez',
                'email' => 'rgomez@megawide.com.ph',
                'position_title' => 'Chief Legal Officer',
                'reporting' => 'Edgar Saavedra',
                'emp_no' => '12197',
                'level' => 'Executive',
                'department' => 'LEG',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => null
            ],
            [
                'pid' => 66,
                'is_active' => true,
                'firstname' => 'Ricky Boy',
                'lastname' => 'Cabatu',
                'nickname' => 'Ricky',
                'name' => 'Ricky Boy Cabatu',
                'email' => 'rbcabatu@megawide.com.ph',
                'position_title' => 'Senior Legal Counsel, Corp Secretarial & Compliance',
                'reporting' => 'Raymund Jay Gomez',
                'emp_no' => '47467',
                'level' => 'Manager',
                'department' => 'LEG',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/ricky.png'
            ],
            [
                'pid' => 66,
                'is_active' => true,
                'firstname' => 'Kristine Aira',
                'lastname' => 'Inao',
                'nickname' => 'Aira',
                'name' => 'Kristine Aira Inao',
                'email' => 'kainao@megawide.com.ph',
                'position_title' => 'Paralegal',
                'reporting' => 'Raymund Jay Gomez',
                'emp_no' => '13759',
                'level' => 'Rank & File',
                'department' => 'LEG',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/aira.png'
            ],
            [
                'pid' => 66,
                'is_active' => true,
                'firstname' => 'Nica Marsha',
                'lastname' => 'Gasapo',
                'nickname' => 'Nica',
                'name' => 'Nica Marsha Gasapo',
                'email' => 'nmgasapo@megawide.com.ph',
                'position_title' => 'Legal Counsel',
                'reporting' => 'Raymund Jay Gomez',
                'emp_no' => '53152',
                'level' => 'Manager',
                'department' => 'LEG',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/nica.png'
            ],
            [
                'pid' => 69,
                'is_active' => true,
                'firstname' => 'Neil Kirby',
                'lastname' => 'Ada',
                'nickname' => 'Kirby',
                'name' => 'Neil Kirby Ada',
                'email' => 'nkada@megawide.com.ph',
                'position_title' => 'Associate Legal Counsel',
                'reporting' => 'Nica Marsha Gasapo',
                'emp_no' => '19823',
                'level' => 'Manager',
                'department' => 'LEG',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/kirby.png'
            ],
            [
                'pid' => 69,
                'is_active' => true,
                'firstname' => 'Laila',
                'lastname' => 'Antoniano',
                'nickname' => 'Lei',
                'name' => 'Laila Antoniano',
                'email' => 'lantoniano@megawide.com.ph',
                'position_title' => 'Paralegal',
                'reporting' => 'Nica Marsha Gasapo',
                'emp_no' => '61251',
                'level' => 'Rank & File',
                'department' => 'LEG',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/leigasapo.png'
            ],
            [
                'pid' => 69,
                'is_active' => true,
                'firstname' => 'Giancharlie',
                'lastname' => 'Go',
                'nickname' => 'Giggy',
                'name' => 'Giancharlie Go',
                'email' => 'ggo@megawide.com.ph',
                'position_title' => 'Senior Legal Counsel',
                'reporting' => 'Raymund Jay Gomez',
                'emp_no' => '20076',
                'level' => 'Manager',
                'department' => 'LEG',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/giggy.png'
            ],
            [
                'pid' => 72,
                'is_active' => true,
                'firstname' => 'Janelle Caryn',
                'lastname' => 'Dela Cruz',
                'nickname' => 'Janelle',
                'name' => 'Janelle Caryn Dela Cruz',
                'email' => 'jcdelacruz@megawide.com.ph',
                'position_title' => 'Associate Legal Counsel',
                'reporting' => 'Giancharlie Go',
                'emp_no' => '19894',
                'level' => 'Manager',
                'department' => 'LEG',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/janelle.png'
            ],
            [
                'pid' => 66,
                'is_active' => true,
                'firstname' => 'Niño Jovit',
                'lastname' => 'Jimenez',
                'nickname' => 'Nino',
                'name' => 'Niño Jovit Jimenez',
                'email' => 'njjimenez@megawide.com.ph',
                'position_title' => 'Corporate Regulatory Officer',
                'reporting' => 'Gomez, Raymund Jay (Bom)',
                'emp_no' => '12895',
                'level' => 'Supervisor / Officer',
                'department' => 'LEG',
                'business_unit' => 'CORP',
                'company' => 'MEGAWIDE',
                'image' => 'org-structure/ninojimenez.png'
            ],
            // ... additional rows from CSV follow the same structure ...
        ];

        DB::table('org_structures')->truncate();

        foreach ($data as $item) {
            \App\Models\OrgStructure::create($item);
        }
    }

}
