<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SubfunctionDescriptionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['id' => 1, 'subfunction_position_id' => 1, 'description' => "Set and communicate Megawide's long-term vision and strategic goals across all business units, ensuring alignment with direction.", 'order_id' => 1],
            ['id' => 3, 'subfunction_position_id' => 1, 'description' => "Regularly review performance against strategic objectives.", 'order_id' => 2],
            ['id' => 5, 'subfunction_position_id' => 2, 'description' => "Lead business units to drive performance by conducting regular review of business performance, including the Financials and Operational KPIs.", 'order_id' => 1],
            ['id' => 9, 'subfunction_position_id' => 3, 'description' => "Serve as the key liaison with the Board of Directors and shareholders, presenting to them Strategic Updates, Business Plans and Financial Results.", 'order_id' => 1],
            ['id' => 12, 'subfunction_position_id' => 4, 'description' => "Champion core values and a high-performance culture.", 'order_id' => 1],
            ['id' => 13, 'subfunction_position_id' => 4, 'description' => "Guide succession planning and talent development.", 'order_id' => 2],
            ['id' => 14, 'subfunction_position_id' => 4, 'description' => "Promote ethical leadership, inclusion, and innovation.", 'order_id' => 3],
            ['id' => 15, 'subfunction_position_id' => 5, 'description' => "Oversee the implementation and integration of the enterprise risk management (ERM) framework across all business units.", 'order_id' => 1],
            ['id' => 16, 'subfunction_position_id' => 5, 'description' => "Review top risks, mitigation plans, and ensure alignment with the company's risk appetite.", 'order_id' => 2],
            ['id' => 17, 'subfunction_position_id' => 5, 'description' => "Uphold corporate governance standards, regulatory compliance, and board-approved policies.", 'order_id' => 3],
            ['id' => 18, 'subfunction_position_id' => 5, 'description' => "Promote a strong risk-aware culture and ethical leadership throughout the organization.", 'order_id' => 4],
            ['id' => 19, 'subfunction_position_id' => 6, 'description' => "Represent Megawide in public forums, government engagements, and investor events.", 'order_id' => 1],
            ['id' => 20, 'subfunction_position_id' => 6, 'description' => "Maintain strong relationships with key stakeholders, including partners, regulators, and investors, ensuring transparent and consistent communication.", 'order_id' => 2],
            ['id' => 21, 'subfunction_position_id' => 7, 'description' => "Identify, map, and document key business processes across the organization.", 'order_id' => 1],
            ['id' => 22, 'subfunction_position_id' => 7, 'description' => "Develop standardized process flowcharts, standard operating procedures (SOPs), and workflow diagrams.", 'order_id' => 2],
            ['id' => 23, 'subfunction_position_id' => 7, 'description' => "Ensure process documentation is accessible, up-to-date, and aligned with organizational standards.", 'order_id' => 3],
            ['id' => 24, 'subfunction_position_id' => 8, 'description' => "Analyze and optimize inefficient processes.", 'order_id' => 1],
            ['id' => 25, 'subfunction_position_id' => 8, 'description' => "Implement automation tools (e.g., robotics process automation) to reduce manual tasks.", 'order_id' => 2],
            ['id' => 26, 'subfunction_position_id' => 8, 'description' => "Measure and report process improvements.", 'order_id' => 3],
            ['id' => 27, 'subfunction_position_id' => 9, 'description' => "Track process performance using KPIs and dashboards.", 'order_id' => 1],
            ['id' => 28, 'subfunction_position_id' => 9, 'description' => "Ensure processes comply with company policies and regulations.", 'order_id' => 2],
            ['id' => 29, 'subfunction_position_id' => 9, 'description' => "Identify and mitigate process risks.", 'order_id' => 3],
            ['id' => 30, 'subfunction_position_id' => 10, 'description' => "Coordinate with departments for process changes.", 'order_id' => 1],
            ['id' => 31, 'subfunction_position_id' => 10, 'description' => "Conduct training for new or updated processes to ensure smooth adoption of new workflows.", 'order_id' => 2],
            ['id' => 32, 'subfunction_position_id' => 11, 'description' => "Develop and enforce security policies, protocols, and procedures for office security.", 'order_id' => 1],
            ['id' => 33, 'subfunction_position_id' => 11, 'description' => "Manage incident response such as but not limited to theft, vandalism, trespassing, and workplace violence.", 'order_id' => 2],
            ['id' => 34, 'subfunction_position_id' => 11, 'description' => "Process gate pass and permit requests for the ingress and egress of people, materials, and equipment.", 'order_id' => 3],
            ['id' => 35, 'subfunction_position_id' => 12, 'description' => "Supervise daily cleaning for office, restrooms, pantry, and studio through regular inspections.", 'order_id' => 1],
            ['id' => 36, 'subfunction_position_id' => 12, 'description' => "Ensure waste collection, disposal, and segregation are regularly implemented by conducting regular inspections.", 'order_id' => 2],
            ['id' => 37, 'subfunction_position_id' => 12, 'description' => "Maintain supply levels for cleaning and sanitation products.", 'order_id' => 3],
            ['id' => 38, 'subfunction_position_id' => 13, 'description' => "Implement office-level health and safety practices (e.g., fire exits, first aid), and emergency response protocols.", 'order_id' => 1],
            ['id' => 39, 'subfunction_position_id' => 13, 'description' => "Equip employees with emergency response tools and equipment.", 'order_id' => 2],
            ['id' => 40, 'subfunction_position_id' => 13, 'description' => "Conduct regular safety drills and mandatory health and safety trainings to ensure compliance with DOLE and BFP safety regulations.", 'order_id' => 3],
            ['id' => 41, 'subfunction_position_id' => 14, 'description' => "Maintain supply levels for pantry (e.g., food, water, disposable utensils) and coffee nook needed for day-to-day use.", 'order_id' => 1],
            ['id' => 42, 'subfunction_position_id' => 14, 'description' => "Prepare and serve meals, snacks, or beverages for internal meetings at 11F CEO office and 11F Boardroom.", 'order_id' => 2],
            ['id' => 43, 'subfunction_position_id' => 14, 'description' => "Manage the scheduling, set-up, and user-friendly access of meeting rooms, pods (10F and 11F), 11F Corporate Boardroom, and studio.", 'order_id' => 3],
            ['id' => 44, 'subfunction_position_id' => 14, 'description' => "Track and ensure timely payment of office utility bills (e.g., landline, water, and electricity) to maintain uninterrupted facility operations.", 'order_id' => 4],
            ['id' => 45, 'subfunction_position_id' => 14, 'description' => "Oversee contract review and renewal with the lessor (RSTP), including sublease to lessee (Citicore).", 'order_id' => 5],
            ['id' => 46, 'subfunction_position_id' => 14, 'description' => "Track inventory of office fixed assets which includes furniture and fixtures and equipment.", 'order_id' => 6],
            ['id' => 47, 'subfunction_position_id' => 14, 'description' => "Manage parking application and allocation.", 'order_id' => 7],
            ['id' => 48, 'subfunction_position_id' => 15, 'description' => "Monitor preventive maintenance and repairs for office equipment  (e.g., aircons - Rockwell Land Corporation, appliances - vendor) including coordinating with respective vendors for repairs and maintenance.", 'order_id' => 1],
            ['id' => 49, 'subfunction_position_id' => 15, 'description' => "Ensure pest control services are administered and monitored in the office periodically through the building administrator for their provided third-party services.", 'order_id' => 2],
            ['id' => 50, 'subfunction_position_id' => 15, 'description' => "Ensure studio equipment (i.e, sound system, intercoms) is properly maintained.", 'order_id' => 3],
            ['id' => 51, 'subfunction_position_id' => 16, 'description' => "Develop and finalize renovation designs, layouts, and work plans, ensuring alignment with company needs and building guidelines.", 'order_id' => 1],
            ['id' => 52, 'subfunction_position_id' => 16, 'description' => "Monitor construction which covers schedule and budget.", 'order_id' => 2],
            ['id' => 53, 'subfunction_position_id' => 16, 'description' => "Conduct final inspections and manage punch lists of renovated areas.", 'order_id' => 3],
            // ['id' => 54, 'subfunction_position_id' => 17, 'description' => "Source and select qualified vendors for maintenance, housekeeping, security, other facility services, and renovation and upgrade works.", 'order_id' => 1],
            // ['id' => 55, 'subfunction_position_id' => 17, 'description' => "Coordinate with vendors to ensure compliance with service agreements and performance standards.", 'order_id' => 2],
            // ['id' => 56, 'subfunction_position_id' => 17, 'description' => "Manage vendor contracts, including renewals, performance evaluations, and termination when necessary.", 'order_id' => 3],
            ['id' => 57, 'subfunction_position_id' => 18, 'description' => "Design, maintain, and optimize network infrastructure across on-premise and cloud environments (e.g., Azure, MS Domain).", 'order_id' => 1],
            ['id' => 58, 'subfunction_position_id' => 18, 'description' => "Monitor network and server performance and resolve connectivity issues.", 'order_id' => 2],
            ['id' => 59, 'subfunction_position_id' => 19, 'description' => "Set up IT hardware specifications, users, and purchasing guidelines.", 'order_id' => 1],
            ['id' => 60, 'subfunction_position_id' => 20, 'description' => "Network: Install and regularly update firewalls and endpoint protection systems to prevent unauthorized access and malware threats (updated via outsourced Action 1 patching tool).", 'order_id' => 1],
            ['id' => 61, 'subfunction_position_id' => 20, 'description' => "Software: Install anti-virus and ensure that these are updated based on the latest version (updated via outsourced Action 1 patching tool).", 'order_id' => 2],
            ['id' => 62, 'subfunction_position_id' => 20, 'description' => "Campaign: Send regular reminders, system notifications to users, and conduct awareness campaigns to prevent phishing, weak passwords, and unsafe digital practices.", 'order_id' => 3],
            ['id' => 63, 'subfunction_position_id' => 22, 'description' => "Administer on-premise and cloud-based databases, file servers, and storage systems to ensure data availability and performance.", 'order_id' => 1],
            ['id' => 64, 'subfunction_position_id' => 22, 'description' => "Perform regular system backups, implement disaster recovery procedures, and execute archiving practices.", 'order_id' => 2],
            ['id' => 65, 'subfunction_position_id' => 22, 'description' => "Implement file management systems and standards and conduct periodic compliance audits.", 'order_id' => 3],
            // ['id' => 66, 'subfunction_position_id' => 23, 'description' => "Administer and provide technical support to ERP systems (i.e., SAP) ensuring operational continuity and user assistance.", 'order_id' => 1],
            ['id' => 67, 'subfunction_position_id' => 24, 'description' => "Develop apps using tools to automate workflows, digitalize processes, and integrate with Microsoft 365 systems.", 'order_id' => 1],
            ['id' => 68, 'subfunction_position_id' => 25, 'description' => "Engage in industry events and forums to build stakeholder connections, explore new markets, and identify partners for joint ventures or consortiums for new business .", 'order_id' => 1],
            ['id' => 69, 'subfunction_position_id' => 25, 'description' => "Build and maintain long-term relationships with key stakeholders through regular communication.", 'order_id' => 2],
            ['id' => 70, 'subfunction_position_id' => 26, 'description' => "Conduct preliminary analysis to assess project feasibility, including financial models, valuations, and market research.", 'order_id' => 1],
            // ['id' => 72, 'subfunction_position_id' => 27, 'description' => "Manage the full bid process—coordinate with the client, managing workstreams, gather inputs, and submit a complete and compliant proposal.", 'order_id' => 1],
            // ['id' => 73, 'subfunction_position_id' => 28, 'description' => "Create business plans for new or existing projects, ensuring alignment with strategy and compliance.", 'order_id' => 1],
            // ['id' => 74, 'subfunction_position_id' => 28, 'description' => "Coordinate with internal teams and external stakeholders (e.g., Legal, Finance, LGU, government agencies) to secure required documents and approvals to progress the project up to the construction stage.", 'order_id' => 2],
            // ['id' => 75, 'subfunction_position_id' => 28, 'description' => "Oversee creation and training of new business units and ensure proper transition.", 'order_id' => 3],
            // ['id' => 76, 'subfunction_position_id' => 29, 'description' => "Provide guidance and inputs for general business development initiatives of the business unit, as needed. Participate in regular meetings on key projects.", 'order_id' => 1],
            ['id' => 77, 'subfunction_position_id' => 30, 'description' => "Monitor and interpret changes in national and local regulations affecting the company and its subsidiaries.", 'order_id' => 1],
            ['id' => 78, 'subfunction_position_id' => 30, 'description' => "Represent the company in engagements with government officials and regulatory agencies.", 'order_id' => 2],
            ['id' => 79, 'subfunction_position_id' => 30, 'description' => "Participate in business councils, chambers, and industry associations.", 'order_id' => 3],
            ['id' => 80, 'subfunction_position_id' => 30, 'description' => "Advocate for favorable business policies through position papers, public consultations, lobbying efforts, or feedback from internal experts.", 'order_id' => 4],
            // ['id' => 81, 'subfunction_position_id' => 31, 'description' => "Map and manage relationships with key external stakeholders (government agencies and units, NGOs, business groups, civic organizations, among others).", 'order_id' => 1],
            // ['id' => 82, 'subfunction_position_id' => 31, 'description' => "Facilitate stakeholder dialogues or partnerships that align with the company's long-term goals.", 'order_id' => 2],
            ['id' => 83, 'subfunction_position_id' => 32, 'description' => "Manage corporate issues and crises, including crisis communication and business continuity, to mitigate reputational damage or operational disruption.", 'order_id' => 1],
            ['id' => 84, 'subfunction_position_id' => 32, 'description' => "Assist in managing business unit crises to mitigate reputational damage or operational disruption.", 'order_id' => 2],
            ['id' => 96, 'subfunction_position_id' => 37, 'description' => "Develop employee newsletters and oversee employee intranet site.", 'order_id' => 1],
            // ['id' => 98, 'subfunction_position_id' => 38, 'description' => "Build and maintain a media contact database for proactive and reactive media engagement.", 'order_id' => 1],
            // ['id' => 99, 'subfunction_position_id' => 38, 'description' => "Organize press briefings, site tours, or interviews featuring key executives and prepare media kits, press releases, op-eds, and thought leadership articles.", 'order_id' => 2],
            // ['id' => 105, 'subfunction_position_id' => 40, 'description' => "Draft leadership messages for speeches, public statements, or executive interviews.", 'order_id' => 1],
            // ['id' => 106, 'subfunction_position_id' => 40, 'description' => "Manage speaking engagements and public appearances of top executives.", 'order_id' => 2],
            // ['id' => 107, 'subfunction_position_id' => 40, 'description' => "Prepare leadership communication toolkits for cascading messages to internal teams.", 'order_id' => 3],
            ['id' => 108, 'subfunction_position_id' => 41, 'description' => "Prepare the Parent and Consolidated Annual Operating Plan (AOP) and long-term financial plan.", 'order_id' => 1],
            ['id' => 109, 'subfunction_position_id' => 41, 'description' => "Analyze financial performance and prepare variance analysis against AOP.", 'order_id' => 2],
            ['id' => 110, 'subfunction_position_id' => 41, 'description' => "Support business units with scenario modeling and strategic financial projections.", 'order_id' => 3],
            ['id' => 111, 'subfunction_position_id' => 42, 'description' => "Conduct financial modeling and valuation for investments, acquisitions, and projects.", 'order_id' => 1],
            ['id' => 112, 'subfunction_position_id' => 42, 'description' => "Lead finance transactions on both equity and debt fund raising, and corporate restructuring.", 'order_id' => 2],
            ['id' => 113, 'subfunction_position_id' => 42, 'description' => "Prepare financial analyses for capital structure and capital allocation decisions.", 'order_id' => 3],
            ['id' => 114, 'subfunction_position_id' => 42, 'description' => "Lead financial due diligence and support strategy execution.", 'order_id' => 4],
            ['id' => 115, 'subfunction_position_id' => 42, 'description' => "Manage key stakeholders such as Banks, Credit Agencies, Counsels, Regulators.", 'order_id' => 5],
            ['id' => 116, 'subfunction_position_id' => 43, 'description' => "Prepare and consolidate cash flow for AOP and long-term financial plan on both Parent and Consolidated level.", 'order_id' => 1],
            ['id' => 117, 'subfunction_position_id' => 43, 'description' => "Monitor and manage weekly cash flow to maintain liquidity for operational and strategic investments while optimizing return on excess cash thru short term investments.", 'order_id' => 2],
            ['id' => 118, 'subfunction_position_id' => 43, 'description' => "Execute and record treasury transactions covering receipts and disbursements.", 'order_id' => 3],
            ['id' => 119, 'subfunction_position_id' => 43, 'description' => "Administer the debt portfolio, including credit line set-up, timely principal and interest payments, and compliance with all covenant and reporting obligations.", 'order_id' => 4],
            ['id' => 120, 'subfunction_position_id' => 43, 'description' => "Manage banking relationships.", 'order_id' => 5],
            ['id' => 121, 'subfunction_position_id' => 43, 'description' => "Set-up Dividend and Management Fee policy of subsidiaries and monitor compliance.", 'order_id' => 6],
            ['id' => 122, 'subfunction_position_id' => 43, 'description' => "Monitor economic indicators, market trends, and geopolitical events and anticipate and respond to potential impacts on the organization's financial strategy.", 'order_id' => 7],
            ['id' => 123, 'subfunction_position_id' => 44, 'description' => "Set up and implement the Accounting System, including the accounting manual and enterprise resource planning (ERP) software.", 'order_id' => 1],
            ['id' => 124, 'subfunction_position_id' => 44, 'description' => "Process billings to customers (SBUs) and process request for payments.", 'order_id' => 2],
            ['id' => 125, 'subfunction_position_id' => 44, 'description' => "Prepare statutory and management financial reports in compliance with the accounting manual (Parent & Consolidated).", 'order_id' => 3],
            ['id' => 126, 'subfunction_position_id' => 44, 'description' => "Lead external financial audits, secure approval of audited financial statements (FS) from Audit Committee and comply with statutory filings.", 'order_id' => 4],
            ['id' => 127, 'subfunction_position_id' => 45, 'description' => "Develop and implement tax-efficient strategies for Parent & Subsidiaries.", 'order_id' => 1],
            ['id' => 128, 'subfunction_position_id' => 45, 'description' => "File local and national tax returns in a timely and accurate manner and lead close-out of tax audits.", 'order_id' => 2],
            ['id' => 129, 'subfunction_position_id' => 45, 'description' => "Monitor changes in tax laws and regulatory requirements, evaluate financial impact, and conduct relevant trainings.", 'order_id' => 3],
            ['id' => 130, 'subfunction_position_id' => 46, 'description' => "Prepare and submit shareholder communications, such as press releases and earnings reports, and file timely and accurate disclosure to the PSE and SEC.", 'order_id' => 1],
            ['id' => 131, 'subfunction_position_id' => 46, 'description' => "Liaise between Megawide and its shareholders, institutional investors, analysts, and credit rating agencies by organizing and managing investor briefings, annual stockholders' meetings, and other key investor engagements.", 'order_id' => 2],
            ['id' => 132, 'subfunction_position_id' => 46, 'description' => "Monitor investor sentiment and provide strategic insights to Management.", 'order_id' => 3],
            ['id' => 133, 'subfunction_position_id' => 46, 'description' => "Report on the group's Environmental, Social, and Governance (ESG) performance in compliance with global standards such as SASB, TCFD, GRI.", 'order_id' => 4],
            ['id' => 134, 'subfunction_position_id' => 47, 'description' => "Assist in the review of governance structure on all companies, listed or not, of the board and board committees and charters.", 'order_id' => 1],
            ['id' => 135, 'subfunction_position_id' => 47, 'description' => "Manage corporate secretarial work, maintaining and updating corporate records, minutes, and board resolutions, and certifications for all listed and non-listed companies as well as issue Secretary's certificate when needed.", 'order_id' => 2],
            ['id' => 136, 'subfunction_position_id' => 47, 'description' => "Handle incorporation of new companies, manage relevant filings, and oversee corporate housekeeping activities.", 'order_id' => 3],
            ['id' => 137, 'subfunction_position_id' => 47, 'description' => "Comply with the relevant laws and regulations for all companies, as required.", 'order_id' => 4],
            ['id' => 138, 'subfunction_position_id' => 47, 'description' => "Protect and manage trademarks, copyrights, and other intellectual properties.", 'order_id' => 5],
            ['id' => 139, 'subfunction_position_id' => 47, 'description' => "Facilitate processing of select permits and licenses of subsidiaries based on the annual regulatory permits plan.", 'order_id' => 6],
            ['id' => 140, 'subfunction_position_id' => 48, 'description' => "Draft, review, analyze, and negotiate a wide range of contracts and other legal documents for new businesses in Corporate, such as concession agreements, public-private contracts, joint venture agreements, and shareholder agreements, among others.", 'order_id' => 1],
            ['id' => 141, 'subfunction_position_id' => 48, 'description' => "Provide contract advisory services to subsidiaries, as requested, such as review of contracts, claims letter, and other legal correspondences.", 'order_id' => 2],
            ['id' => 142, 'subfunction_position_id' => 48, 'description' => "Establish standard contract templates needed by the subsidiaries for use across the group, including cascading and providing training to them in using these templates.", 'order_id' => 3],
            ['id' => 143, 'subfunction_position_id' => 48, 'description' => "Establish repository system for use across the group, including cascading and providing training to them in using the system.", 'order_id' => 4],
            ['id' => 144, 'subfunction_position_id' => 49, 'description' => "Engage and supervise external counsels to perform all litigation, including arbitration and other modes of dispute resolution, and claims. Monitor strategy, case status, costs, and outcomes, coordinating them with the subsidiaries.", 'order_id' => 1],
            ['id' => 145, 'subfunction_position_id' => 49, 'description' => "Oversee employee discipline cases, particularly employee termination cases, for subsidiaries, and provide relevant trainings as requested.", 'order_id' => 2],
            ['id' => 146, 'subfunction_position_id' => 49, 'description' => "Represent the company in legal proceedings, particularly for minor cases, as required.", 'order_id' => 3],
            ['id' => 147, 'subfunction_position_id' => 50, 'description' => "Provide legal due diligence and transaction support for mergers and acquisitions, joint ventures, or divestments.", 'order_id' => 1],
            ['id' => 148, 'subfunction_position_id' => 50, 'description' => "Ensure compliance with SEC, PSE, PCC, and other relevant regulatory bodies during and after the transactions.", 'order_id' => 2],
            ['id' => 149, 'subfunction_position_id' => 50, 'description' => "Support fund raising activities of MCC and its subsidiaries.", 'order_id' => 3],
            ['id' => 150, 'subfunction_position_id' => 51, 'description' => "Handle land purchase, transfer of title, and other related services such as land conversion.", 'order_id' => 1],
            ['id' => 151, 'subfunction_position_id' => 52, 'description' => "Provide expert guidance on legal matters as aligned to the strategic direction in regular meetings, including relevant standards, guidelines, tools, and templates, across the group.", 'order_id' => 1],
            ['id' => 152, 'subfunction_position_id' => 52, 'description' => "Monitor legal compliance at the subsidiary level, ensuring contracts are reviewed, enforced, and met agreed standards.", 'order_id' => 2],
            ['id' => 153, 'subfunction_position_id' => 53, 'description' => "Facilitate organizational design that support business growth.", 'order_id' => 1],
            ['id' => 154, 'subfunction_position_id' => 53, 'description' => "Assist in defining and aligning roles, skills, and behaviors required to drive organizational and individual success.", 'order_id' => 2],
            ['id' => 155, 'subfunction_position_id' => 53, 'description' => "Ensure strategic workforce planning is in place for new projects and business units.", 'order_id' => 3],
            ['id' => 156, 'subfunction_position_id' => 54, 'description' => "Manage and oversee the recruitment of senior management roles across the group and corporate roles.", 'order_id' => 1],
            ['id' => 157, 'subfunction_position_id' => 54, 'description' => "Develop employer branding and recruitment marketing strategies at the group level.", 'order_id' => 2],
            ['id' => 158, 'subfunction_position_id' => 55, 'description' => "Identify high-potential employees across subsidiaries.", 'order_id' => 1],
            ['id' => 159, 'subfunction_position_id' => 55, 'description' => "Design and manage executive development, coaching, and succession programs.", 'order_id' => 2],
            ['id' => 160, 'subfunction_position_id' => 55, 'description' => "Design and manage career development for non-executives.", 'order_id' => 3],
            // ['id' => 162, 'subfunction_position_id' => 56, 'description' => "Set performance standards and guidelines for Corporate and subsidiaries.", 'order_id' => 1],
            // ['id' => 163, 'subfunction_position_id' => 56, 'description' => "Implement and monitor a performance management system (PMS) for Corporate and leadership roles by aligning performance metrics with business KPIs.", 'order_id' => 2],
            ['id' => 164, 'subfunction_position_id' => 57, 'description' => "Implement and oversee group-wide HR systems (HRIS, payroll tools, etc.).", 'order_id' => 1],
            ['id' => 165, 'subfunction_position_id' => 57, 'description' => "Maintain secure and organized filing systems (both digital and physical).", 'order_id' => 2],
            ['id' => 166, 'subfunction_position_id' => 57, 'description' => "Administer compensation and benefits for Corporate, executive, and expatriate employees.", 'order_id' => 3],
            // ['id' => 167, 'subfunction_position_id' => 58, 'description' => "Evaluate employee development needs to identify skill gaps and growth opportunities.", 'order_id' => 1],
            // ['id' => 168, 'subfunction_position_id' => 58, 'description' => "Design targeted learning frameworks covering leadership development (for Corporate and subsidiaries), technical training (for Corporate), and cross-subsidiary capability building.", 'order_id' => 2],
            // ['id' => 169, 'subfunction_position_id' => 58, 'description' => "Establish partnerships with training institutions and consultants for enterprise-wide learning initiatives.", 'order_id' => 3],
            ['id' => 170, 'subfunction_position_id' => 59, 'description' => "Conduct periodic employee engagement surveys, which include leadership, job satisfaction, work environment.", 'order_id' => 1],
            ['id' => 171, 'subfunction_position_id' => 59, 'description' => "Lead culture alignment initiatives and group-wide employee engagement programs.", 'order_id' => 2],
            ['id' => 172, 'subfunction_position_id' => 59, 'description' => "Promote a learning culture across the organization.", 'order_id' => 3],
            ['id' => 173, 'subfunction_position_id' => 59, 'description' => "Organize corporate events that reinforce group identity and incorporate Megawide culture.", 'order_id' => 4],
            // ['id' => 174, 'subfunction_position_id' => 60, 'description' => "Implement and oversee group-wide HR systems (HRIS, payroll tools, etc.).", 'order_id' => 1],
            // ['id' => 175, 'subfunction_position_id' => 60, 'description' => "Maintain secure and organized filing systems (both digital and physical).", 'order_id' => 2],
            // ['id' => 176, 'subfunction_position_id' => 60, 'description' => "Consolidate and analyze HR metrics from subsidiaries (turnover, headcount, cost).", 'order_id' => 3],
            // ['id' => 177, 'subfunction_position_id' => 60, 'description' => "Use data to inform workforce and talent decisions at the group level.", 'order_id' => 4],
            ['id' => 178, 'subfunction_position_id' => 61, 'description' => "Provide expert guidance and HR policies, including relevant standards, guidelines, tools, and templates, across the group.", 'order_id' => 1],
            ['id' => 179, 'subfunction_position_id' => 61, 'description' => "Monitor HR compliance and audit readiness at the subsidiary level, ensuring deliverables are within given timeline and meet agreed standards.", 'order_id' => 2],
            ['id' => 180, 'subfunction_position_id' => 61, 'description' => "Facilitate shared learning and best practice exchange among subsidiaries.", 'order_id' => 3],
            ['id' => 181, 'subfunction_position_id' => 61, 'description' => "Provide compliance support, including direction on labor compliance and regulatory adherence and guidance to subsidiaries on whether labor matters should be handled in-house or outsourced.", 'order_id' => 4],
            ['id' => 182, 'subfunction_position_id' => 62, 'description' => "Manage travel arrangements, courier services, vehicle scheduling, communications and vehicle concerns, and office supplies.", 'order_id' => 1],
            ['id' => 183, 'subfunction_position_id' => 62, 'description' => "Process purchase requisitions, issue purchase orders, coordinate payments, and monitor deliveries and inventories wisely of required goods (office equipment, office supplies, food) of Corporate.", 'order_id' => 2],
            ['id' => 184, 'subfunction_position_id' => 63, 'description' => "Evaluate the efficiency and effectiveness of existing internal controls.", 'order_id' => 1],
            ['id' => 185, 'subfunction_position_id' => 63, 'description' => "Recommend improvements to processes, resource utilization, and internal controls.", 'order_id' => 2],
            ['id' => 186, 'subfunction_position_id' => 64, 'description' => "Verify accuracy and integrity of financial transactions and reports.", 'order_id' => 1],
            ['id' => 187, 'subfunction_position_id' => 64, 'description' => "Assess compliance with financial regulations, company policies, and accounting standards.", 'order_id' => 2],
            ['id' => 188, 'subfunction_position_id' => 64, 'description' => "Evaluate the high risk and fraud areas in financial statements, assess key internal controls, and test transactions and account balances for accuracy and completeness.", 'order_id' => 3],
            ['id' => 189, 'subfunction_position_id' => 65, 'description' => "Audit IT general controls, cybersecurity practices, and data governance.", 'order_id' => 1],
            ['id' => 190, 'subfunction_position_id' => 65, 'description' => "Evaluate system reliability, access controls, and disaster recovery plans.", 'order_id' => 2],
            ['id' => 191, 'subfunction_position_id' => 66, 'description' => "Investigate whistleblower reports, irregularities, or suspected fraud in collaboration with Legal and Human Resources.", 'order_id' => 1],
            ['id' => 192, 'subfunction_position_id' => 21, 'description' => "Set up of required software and applications on every new laptop and ensure all installed programs are up to date (updated via outsourced Action 1 patching tool).", 'order_id' => 1],
            ['id' => 193, 'subfunction_position_id' => 21, 'description' => "Collect and report of all data related to inventory of IT software assets in corporate, including SBU consolidation; Coordinate with Procurement for the annual license renewals.", 'order_id' => 2],
            ['id' => 194, 'subfunction_position_id' => 26, 'description' => "Present research findings, trends, and recommendations to support strategic decisions.", 'order_id' => 2],
            ['id' => 197, 'subfunction_position_id' => 53, 'description' => "Set performance management system for the group; Oversee its implementation for Corporate and leadership roles by aligning performance metrics with business KPIs.", 'order_id' => 4],
            ['id' => 198, 'subfunction_position_id' => 55, 'description' => "Evaluate employee development needs to identify skill gaps and growth opportunities.", 'order_id' => 4],
            ['id' => 199, 'subfunction_position_id' => 55, 'description' => "Design targeted learning frameworks covering leadership development (for Corporate and subsidiaries), technical training (for Corporate), and cross-subsidiary capability building.", 'order_id' => 5],
            ['id' => 200, 'subfunction_position_id' => 55, 'description' => "Establish partnerships with training institutions and consultants for enterprise-wide learning initiatives.", 'order_id' => 6],
            ['id' => 201, 'subfunction_position_id' => 39, 'description' => "Organize press briefings, site tours, or interviews featuring key executives and prepare media kits, press releases, op-eds, and thought leadership articles.", 'order_id' => 1],
            ['id' => 202, 'subfunction_position_id' => 67, 'description' => "Define the master brand narrative, personality, and tone of voice of the company and establish how the parent brand relates to its subsidiaries.", 'order_id' => 1],
            ['id' => 203, 'subfunction_position_id' => 68, 'description' => "Design activities and projects that build public awareness and strengthen the brand equity, serving as platform for communication with applicants, vendors & investors.", 'order_id' => 1],
            ['id' => 204, 'subfunction_position_id' => 69, 'description' => "Conceptualize and produce of videos, promotional content, and branded visuals in support to the social media, website, events, reports, and campaigns.", 'order_id' => 1],
            // ['id' => 205, 'subfunction_position_id' => 70, 'description' => "xxx", 'order_id' => 1],
            ['id' => 206, 'subfunction_position_id' => 68, 'description' => "Track perception metrics like brand recall, sentiment, and affinity.", 'order_id' => 2],
            ['id' => 207, 'subfunction_position_id' => 68, 'description' => "Maintain the Company website platform and social media outfits.", 'order_id' => 3],
            // ['id' => 210, 'subfunction_position_id' => 72, 'description' => "xxx", 'order_id' => 1],
            ['id' => 211, 'subfunction_position_id' => 46, 'description' => "Communicate company financial information with stakeholders, ensuring transparency, trust, and alignment with market expectations.", 'order_id' => 5],
            ['id' => 213, 'subfunction_position_id' => 2, 'description' => "Ensure synergy, collaboration, and cross-functional efficiency across departments and units.", 'order_id' => 2],
            ['id' => 214, 'subfunction_position_id' => 14, 'description' => "Source and select qualified vendors for maintenance, housekeeping, security, other facility services, and renovation and upgrade works.", 'order_id' => 7],
            ['id' => 215, 'subfunction_position_id' => 14, 'description' => "Coordinate with vendors to ensure compliance with service agreements and performance standards.", 'order_id' => 8],
            ['id' => 216, 'subfunction_position_id' => 14, 'description' => "Manage vendor contracts, including renewals, performance evaluations, and termination when necessary.", 'order_id' => 9],
            ['id' => 217, 'subfunction_position_id' => 19, 'description' => "Maintain accurate inventory of IT hardware assets for all Corporate locations and users, including issuance, safekeeping, and storage.", 'order_id' => 2],
            ['id' => 218, 'subfunction_position_id' => 74, 'description' => "Manage the full bid process by coordinating with the client, managing workstreams, gathering inputs, and submitting a complete and compliant proposal.", 'order_id' => 1],
            ['id' => 219, 'subfunction_position_id' => 75, 'description' => "Create Business Plan in preparation for the development of the operational management team; Oversee the creation and training of new business units and ensuring proper transition.", 'order_id' => 1],
            ['id' => 220, 'subfunction_position_id' => 75, 'description' => "Provide guidance and inputs for general business development initiatives of the business unit, as needed; Participate in regular meeting on key projects.", 'order_id' => 2],
            ['id' => 221, 'subfunction_position_id' => 30, 'description' => "Map and manage relationships with key external stakeholders (government agencies and units, NGOs, business groups, civic organizations, among others).", 'order_id' => 5],
            ['id' => 222, 'subfunction_position_id' => 30, 'description' => "Facilitate stakeholder dialogues or partnerships that align with the company's long-term goals.", 'order_id' => 6],
            ['id' => 223, 'subfunction_position_id' => 39, 'description' => "Draft leadership messages for speeches, public statements, or executive interviews; Manage speaking engagements and public appearances of top executives.", 'order_id' => 2],
            ['id' => 224, 'subfunction_position_id' => 39, 'description' => "Develop creative messaging for company milestones, partnerships, and initiatives.", 'order_id' => 3],
            ['id' => 225, 'subfunction_position_id' => 67, 'description' => "Develop and update the visual identity system including logos, typography, iconography, and templates; Ensure consistency in its presentation and application and provide feedback and guidance, as needed.", 'order_id' => 2],
            ['id' => 226, 'subfunction_position_id' => 76, 'description' => "Develop crisis communication guidelines, drafting holding statements, Q&A documents, and talking points in coordination with Legal and Corporate Affairs teams.", 'order_id' => 1],
            ['id' => 227, 'subfunction_position_id' => 53, 'description' => "Develop and update the executive and corporate salary structure through benchmarking to ensure competitive and equitable pay.", 'order_id' => 5],
            ['id' => 228, 'subfunction_position_id' => 53, 'description' => "Develop recognition and retention program for key and critical talents.", 'order_id' => 6],
            ['id' => 229, 'subfunction_position_id' => 53, 'description' => "Support leadership transitions and internal promotions.", 'order_id' => 7],
            ['id' => 230, 'subfunction_position_id' => 57, 'description' => "Develop and cascade HR policies and manual, which include the code of conduct.", 'order_id' => 4],
            ['id' => 231, 'subfunction_position_id' => 57, 'description' => "Monitor labor law compliance and regulatory adherence (DOLE, SSS, PhilHealth, etc.).", 'order_id' => 5],
            ['id' => 232, 'subfunction_position_id' => 57, 'description' => "Consolidate and analyze HR metrics from subsidiaries (turnover, headcount, cost).", 'order_id' => 6],
        ];

        // DB::table('subfunction_descriptions')->truncate();

        foreach ($data as $item) {
            \App\Models\SubfunctionDescription::create($item);
        }
    }
}
